### ISSUE TITLE
Tracking: query result cache

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#10010]
**Summary**

Query result cache can help us to get query results faster if the data is not changed for the query.

This is a tracking issue for query result cache.

## Basic
- [x] #10011
- [x] Write and read result from result cache. #10042
- [x] Support cache of multiple tables query. #10158
- [x] Use AST as the cache key. #10165
- [x] Store result cache as parquet. #10187

## Related Tables
- [x] System table: `system.query_cache`. #10159
- [x] Table function: `SELECT * FROM RESULT_SCAN(LAST_QUERY_ID(-2));` #10256

## Optional

- [ ] Garbage collection for result cache.
- [ ] Different compression methods for result cache.
- [ ] Support result cache for compound SQLs. (`INSERT SELECT`, `COPY FROM`, `CREATE SELECT`)

**Comment by RinChanNOWWW** [comment]
Open new issues if we need the optional features.
