### ISSUE TITLE
tracking: replace into

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#10373]
**Summary**

- [x] https://github.com/datafuselabs/databend/pull/10191
- [x] https://github.com/datafuselabs/databend/issues/10370
- [x]  https://github.com/datafuselabs/databend/issues/10372
- [x]  https://github.com/datafuselabs/databend/issues/10371
- [x] #10391

Low-priority
- [x]  distributed replace into  (to be planned)

**Comment by dantengsky** [comment]
for `merge into`, please refer https://github.com/datafuselabs/databend/issues/12595
