### ISSUE TITLE
Tracking: importing large datasets

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10463]
**Summary**
- [ ] COPY INTO hang after a long execution. https://github.com/datafuselabs/databend/issues/10461
- [ ] Query crashed during datax import. https://github.com/datafuselabs/databend/issues/10374
- [ ] Data inconsistency between source table and target table of databend https://github.com/alibaba/DataX/issues/1713
- [ ] DataX writing failed and was rolled back.  https://github.com/alibaba/DataX/issues/1703
- [ ] DataX writing interrupted by NPE. https://github.com/alibaba/DataX/issues/1702
- [ ] DataX writing are hanged. https://github.com/alibaba/DataX/issues/1701
