### ISSUE TITLE
Feature: support `GROUPING SETS` clause.

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#10492]
**Summary**

GROUPING SETS perform the same aggregate across different GROUP BY clauses in a single query.

Related clauses:

- [x] Extended group by: grouping sets. #10534
- [x] Extended group by: cube. #10601
- [x] Extended group by: rollup. #10601
- [x] New function: grouping. #10592
- [x] Docs of the features above. #10638
 
## Reference

- https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUPING-SETS
- https://www.postgresql.org/docs/15/functions-aggregate.html
- https://clickhouse.com/docs/en/sql-reference/statements/select/group-by/#grouping-sets-modifier
- https://duckdb.org/docs/sql/query_syntax/grouping_sets.html
- https://doris.apache.org/zh-CN/community/design/grouping_sets_design/

**Comment by RinChanNOWWW** [comment]
cc @sundy-li

**Comment by sundy-li** [comment]
@RinChanNOWWW 
Do you want to take this task or make it a community task?

GroupSets is easy to implement we just need to union the results I think.

**Comment by RinChanNOWWW** [comment]
I can take it.

**Comment by RinChanNOWWW** [comment]
> GroupSets is easy to implement we just need to union the results I think.

The performance will be bad if we just rewrite it to `UNION`s.

We can extend the aggregation pipeline to achieve this feature.
