### ISSUE TITLE
tracking: FlightSQL  handler

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#10745]
**Summary**

- [ ] query https://github.com/datafuselabs/databend/pull/10732
- [ ] update
- [ ] all types
- [ ] more tests
- [ ] try avoid copy
     - [ ] unsafe
     -  [ ] try `arrow_rs grpc + arrow2 flatbuffer` again:  https://github.com/youngsofun/databend/commit/8713bdf168c5a9386c31125e6f34007b77c94dba
- [ ] ci with JDBC client
- [ ] test with BI tools
    -   [ ] dbeaver
