### ISSUE TITLE
Tracking: window function

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#10810]
**Summary**

## Main targets

- [x] initial impl window function
	- [x] https://github.com/datafuselabs/databend/pull/10700
    - [x] https://github.com/datafuselabs/databend/pull/10772
    - [x] https://github.com/datafuselabs/databend/pull/10791
- [x] add more tests
- [x] support range frame
	- [x] initial support range frame #10911
	- [x] range frame supports all number types #11002 
- [x] support more complicated window syntax
	- [x] named window #10897 
	- [x] inherited named window #10934  
	- [x] support window function in order by clause #10989 
- [x] add docs #11013
- [x] General window functions. #11148

## TPC-DS Related.

- [x] Support aggregation function in window function (includes `grouping`). #10887

**Comment by youngsofun** [comment]
I`d like to try percent_rank/cume_dist/ntile If no one else is working on them.

**Comment by ArberSephirotheca** [comment]
Hi, can I work the first_value window func ?

**Comment by ariesdevil** [comment]
> Hi, can I work the first_value window func ?↳

Sure and welcome :）
