### ISSUE TITLE
unify `copy into table ` implements for parquet

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#11158]
suppose the dest table is `my_table(c1 int, c2  string)`

- [x] ParquetTable avoid OOM like Copy https://github.com/datafuselabs/databend/pull/11165
- [x] rewrite `copy into my_table from @my_stage` into `copy into my_table from (select c1, c2 from @my_stage)`。https://github.com/datafuselabs/databend/pull/11173
- [x] optimize for small parquet files https://github.com/datafuselabs/databend/pull/11231
- [ ] rewrite `insert with attachment` to copy 
     - [x] support `copy into my_table(c1, c2) from @my_stage`  (a feature by itself  and  needed to deal with insert placeholder `insert into my_table valuse (1, ?, 2, ?)`)
     - [ ] add the flag `commit_paths` and  `overwrite` in CopyOption

## 'from @my_stage ' vs  'from select * from @my_stage '

current 'copy into my_table from @my_stage '  has some features that make it if with the latter: 

1. file_level auto-project  
2. file_level auto-cast 

these are useful to tolerate schema diff between table and file and between file and file (which `file_level` means).
for example, those files can be loaded to `my_table(c1 int, c2  string)` in one copy op:

parquet1 (c1 int, c2  string) -- Normal
parquet2 (c2 string, c1 int) -- project: reorder
parquet3 (c2 string, c1 int, c3) -- project 
parquet4 (c1 string, c2 string) -- auto cast

1. auto-cast is needed.
2. auto-project is convenient and reasonable(think parquet as a JSON, which rely on column names, not order)
3. without `file_level`  'from @my_stage '  should be identical to `copy into my_table from (select c1, c2 from @my_stage)`,
    - note that  generally, in `copy into my_table from (select <projection> from @my_stage)` the column order` <projection>` is use to match table schema, not the names, like insert, otherwise,  `<projection>` may have to alias each expr
4. `file_level` is not as important
    1.  copy without selecting support it because the meta of each file is processed separately while loading each group;  
    2.  copy with selecting have to do more analyze for select stmt based on the inferred schema, and currently reading of array_chunks is based on orders(leaf_ids derived from the inferred file) not names. 

 I think we can abandon the `file_level` for now,  to focus on unifying and optimizing, and consider add it back if we really need it (the overhead is not too big since it is column level).

after rewrite, we still support 

parquet1 (c1 string, c3 xxx,  c2  string) -- static cast/project,
parquet2 (c1 string, c3 xxx, c2  string, c4 xxx) -- allow file-file diff for unused trailing columns, which not affect column ids

**Comment by youngsofun** [comment]
cc @BohuTANG @sundy-li @RinChanNOWWW
