### ISSUE TITLE
Tracking:  aggregating index feature

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#11183]
**Summary**

Description for this feature.

In the DWH, although some approximate queries can reuse data cache to reduce IO overhead, cache has limitations in terms of timeliness and capacity, and also cannot solve the problem of incremental calculation. Pre-aggregation technology in OLAP can effectively reduce data redundancy and using materialized views to implement pre-aggregation is a good choice.

Here, we introduce aggregate indices as a way to implement a materialized view using secondary indices.

There we list some tasks to be done about aggregating index:

- [ ] Create AGGREGATING INDEX,  syntax example: `CREATE AGGREGATING INDEX 
        t_agg_idx ON t 
    (country,count(distinct user),sum(salary));`

- [ ] SHOW INDEXES
- [ ] DROP INDEX
- [ ] REFRESH AGGREGATING INDEX <agg_index_name>  [limit N]
- [ ] Query Auto-Rewrite using `Hybrid Scan`
- [ ] Tests

Refer:
1. https://docs.snowflake.com/en/user-guide/views-materialized
2. https://docs.firebolt.io/sql-reference/commands/create-aggregating-index.html
3. [vldb21-hyperspace](https://wentaowu.github.io/papers/vldb21-hyperspace.pdf)
4. [p2620-winter](http://www.vldb.org/pvldb/vol13/p2620-winter.pdf)

**Comment by ZhiHanZ** [comment]
In snowflake https://15721.courses.cs.cmu.edu/spring2018/slides/25-snowflake.pdf, their pruning 
adopted zonemap https://drive.google.com/file/d/1O13Jubx29MRQ5fxfo9YrwplG_pwCUbZR/view for lightweight small materialized aggregates, and this paper https://amplab.cs.berkeley.edu/wp-content/uploads/2014/05/mod415-sun.pdf might helped them decide how to partition based on feature indexing

**Comment by sundy-li** [comment]
done #13218
