### ISSUE TITLE
Tracking: bitmap functions

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#11219]
**Summary**
Scalar Functions:
- [x] to_bitmap #11097 
- [x] bitmap_from_string #11097 
- [x] bitmap_to_string #11097 
- [x] bitmap_count #11304
- [x] build_bitmap #11304
- [x] bitmap_or
- [x] bitmap_and
- [x] bitmap_xor
- [x] bitmap_not
- [x] bitmap_and_not
- [x] bitmap_subset_limit
- [x] bitmap_subset_in_range
- [x] sub_bitmap
- [x] bitmap_contains 
- [x] bitmap_has_all
- [x] bitmap_has_any
- [x] bitmap_max
- [x] bitmap_min

Aggregate Functions:
- [x] bitmap_union
- [x] bitmap_and_count
- [x] bitmap_and_not_count
- [x] bitmap_xor_count
- [x] bitmap_or_count
- [x] intersect_count
- [x] bitmap_interssect

**Comment by byrantwithyou** [comment]
Hi, I'm new to Databend and I want to contribute. I have a working knowledge of database kernel and Rust. Could you assign some of the tasks in this list to me?

**Comment by byrantwithyou** [comment]
> Hi, I'm new to Databend and I want to contribute. I have a working knowledge of database kernel and Rust. Could you assign some of the tasks in this list to me?

If nobody is doing the same thing, I want to do `bitmap_or`, `bitmap_and`, `bitmap_xor`, `bitmap_not`, `bitmap_and_not` together, because they are kinda similar.

**Comment by ariesdevil** [comment]
@byrantwithyou Thanks for being interested in these funcs, When things are done, I'll put the pr address after the corresponding function.

**Comment by silver-ymz** [comment]
Hello, I'm new to Databend and want to have a try for this. I want to try `bitmap_contains`, `bitmap_has_all`, `bitmap_has_any`, `bitmap_max`, `bitmap_min` together firstly. Could you assign them to me?

**Comment by byrantwithyou** [comment]
I'm so sorry that I couldn't do this task because I'm a little bit busy these days. Please assign it to anyone else.

**Comment by gitccl** [comment]
Hi, I'd like to try `bitmap_or` and `bitmap_and`

**Comment by gitccl** [comment]
Hi @sundy-li , Can `bitmap_hash` use `ahash` as the hash function?

**Comment by sundy-li** [comment]
>  Can bitmap_hash use ahash as the hash function?

Yes， I don't think we should add the extra function `bitmap_hash `, we can support bitmap type in other hash functions.

**Comment by gitccl** [comment]
> 
It seems that `bitmap_hash` isn't the hash of bitmap type, instead it hashes any value, and then constructs a bitmap with the hash value.

**Comment by liangjiawei1110** [comment]
Hello, I am new to Databend and I'd like to try bitmap_subset_limit ,  bitmap_subset_in_range ,  sub_bitmap.

**Comment by ariesdevil** [comment]
> Hello, I am new to Databend and I'd like to try bitmap_subset_limit , bitmap_subset_in_range , sub_bitmap.↳

These three have been implemented by @Mehrbod2002 , you may take others:)

**Comment by Eternity-AIBN** [comment]
Hello, I am new to here. I would like to ask if there is anything left for me to choose from in the Scalar Functions？

**Comment by akoshchiy** [comment]
@ariesdevil Hello! I want to complete the list and have some questions:
1. As I understand, `intersect_count` is the alias of `bitmap_and_count`, isn't it?
2. Is there any explanation/examples of api and behaving  `orthogonal_*` functions?

**Comment by ariesdevil** [comment]
Hi @akoshchiy , thanks for your contribution.

> 1. As I understand, `intersect_count` is the alias of `bitmap_and_count`, isn't it?

The `intersect_count` is diff from `bitmap_and_count`, the syntax is `INTERSECT_COUNT(bitmap_column, column_to_filter, filter_values)`.

1. bitmap_column: The bitmap column. This is the bitmap data you want to perform intersection operations on.
2. column_to_filter: The dimension column for filtering. This is the column you want to filter the bitmap data based on certain conditions.
3. filter_values: The values of the filter dimension column. This variable-length parameter represents different values of the dimension column to filter.

The purpose of the INTERSECT_COUNT function is to first filter the bitmap data based on the column_to_filter and filter_values, then calculate the intersection count between the filtered bitmaps. This can help you find the number of data points satisfying specific conditions within a larger dataset.

```
bendsql :) select tag, bitmap_to_string(user_id) from pv_bitmap where tag in (3,4);
+------+-----------------------------+
| tag  | bitmap_to_string(`user_id`) |
+------+-----------------------------+
|    4 | 1,2,3                       |
|    3 | 1,2,3,4,5                   |
+------+-----------------------------+
2 rows in set (0.012 sec)

bendsql :) select intersect_count(user_id, tag, 3, 4) from pv_bitmap;
+----------------------------------------+
| intersect_count(`user_id`, `tag`, 3, 4)|
+----------------------------------------+
|                                      3 |
+----------------------------------------+
1 row in set (0.014 sec)
```

> 2. Is there any explanation/examples of api and behaving  `orthogonal_*` functions?

The `orthogonal_*` prefixed functions are just same as the original functions without this prefix, except using a different approach to calculation, we not need them now, so I deleted them.

**Comment by ariesdevil** [comment]
We made it, thank you all!
