### ISSUE TITLE
Tracking: functions

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#11220]
**Summary:**
- [x] Bitmap Functions(Priority: High): #11219 
- [x] Window Functions(Priority: Medium): #11148 
- [x] Geo Functions(Priority: Medium): #6390 
- [x] JSON Functions and Operators(Priority: High): #11270 

**FYI:**:
* [How to write scalar functions](https://databend.rs/doc/contributing/how-to-write-scalar-functions)
* [How to write aggregate functions](https://databend.rs/doc/contributing/how-to-write-aggregate-functions)
