### ISSUE TITLE
Tracking: JSON functions and operators

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#11270]
**Summary**

JSON Functions:
- [x] json_array
- [x] json_array_elements
- [x] json_each
- [x] json_typeof
- [x] json_strip_nulls
- [x] json_pretty
- [x] json_path_exists
- [x] json_path_match

JSON Operators:
- [x] `->` Extracts JSON Array or Object with index or key, returning a JSON value.
- [x] `->>` Extracts JSON Array or Object with index or key, returning a string.
- [x] `#>` Extracts JSON Array or Object with path, returning a JSON value.
- [x] `#>>` Extracts JSON Array or Object with path, returning a string.
- [x] `@>` Does the first JSON value contain the second?
- [x] `<@` Is the first JSON value contained in the second?
- [x] `?` Does the key string exist within the JSON Object key?
- [x] `?|` Does any of the keys in the array exist as JSON Object keys?
- [x] `?&` Does all the keys in the array exist as JSON Object keys?
- [x] `@?` Does the JSON path return any item for the JSON?
- [x] `@@` Returns the result of a JSON path predicate check for the specified JSON value.
- [x] `||` Concatenates two JSON values.
- [x] `- text` Deletes a key (and its value) from a JSON object, or matching string value(s) from a JSON array.
- [x] `- integer` Deletes the array element with specified index (negative integers count from the end). Throws an error if JSON value is not an array.
- [x] `#- text[]` Deletes the field or array element at the specified path, where path elements can be either field keys or array indexes.

Refer to the [PostgreSQL JSON functions document](https://www.postgresql.org/docs/16/functions-json.html)

**Comment by ariesdevil** [comment]
@byrantwithyou You can start by picking a few implementations instead of all of them.

**Comment by byrantwithyou** [comment]
I'll focus on the bitmap first.

**Comment by byrantwithyou** [comment]
I'm so sorry that I couldn't do this task because I'm a little bit busy these days. Please assign it to anyone else.

**Comment by b41sh** [comment]
> I'm so sorry that I couldn't do this task because I'm a little bit busy these days. Please assign it to anyone else.

@byrantwithyou It's ok, feel free to come back and contribute when you have time.

**Comment by infdahai** [comment]
I'd like to write some works in a few days.

**Comment by akoshchiy** [comment]
@b41sh As I understand `json_array_elements` looks like `unnest` for `variant`, but I have no idea how to implement `json_each` properly, because it requires to expand data into two columns (key and value). Do you have any ideas?

**Comment by b41sh** [comment]
> @b41sh As I understand `json_array_elements` looks like `unnest` for `variant`, but I have no idea how to implement `json_each` properly, because it requires to expand data into two columns (key and value). Do you have any ideas?

Hi, @akoshchiy Thanks for your continued contributions. 
Databend has [tuple type](https://databend.rs/doc/sql-reference/data-types/data-type-tuple-types), we can put the results of `json_each` into a tuple column. The data type could be `DataType::Tuple(vec![DataType::String, DataType::Variant])`.
`json_array_elements` looks the same as the `unnest` function already implemented and we can reuse the code.

**Comment by akoshchiy** [comment]
@b41sh hello, I have a question about `#>` and `#>>` operators, what kind of type the second operand should be?
It's a `text[]` in postgres, should we use `Array(String)` in databend too? If so, it would be a little ugly in the operands with the array index keys, because we should treat them as ints. (e.g., postgres expr `json_col #> '{a,1,2}'` will be `json_col #> ['a','1','2']` in databend)

**Comment by b41sh** [comment]
> @b41sh hello, I have a question about `#>` and `#>>` operators, what kind of type the second operand should be? It's a `text[]` in postgres, should we use `Array(String)` in databend too? If so, it would be a little ugly in the operands with the array index keys, because we should treat them as ints. (e.g., postgres expr `json_col #> '{a,1,2}'` will be `json_col #> ['a','1','2']` in databend)

Hi, @akoshchiy , Sorry for the late reply. I don't think it's appropriate to use the `Array(String)` type, because there are both `String` and `Int` types in the key path. We can use the `String` type like PostgreSQL and write a simple parser with [nom](https://docs.rs/nom/latest/nom/) to parse out the key path, which doesn't seem to have complex syntax rules and is relatively easy to write.

**Comment by akoshchiy** [comment]
> Hi, @akoshchiy , Sorry for the late reply. I don't think it's appropriate to use the `Array(String)` type, because there are both `String` and `Int` types in the key path. We can use the `String` type like PostgreSQL and write a simple parser with [nom](https://docs.rs/nom/latest/nom/) to parse out the key path, which doesn't seem to have complex syntax rules and is relatively easy to write.

Ok. Simple comma-separated format is enough, isn't it? (e.g. `json_col #> 'a,1,2'`)   As I understand, curly braces is a special syntax for parsing arrays in postgresql.

**Comment by b41sh** [comment]
> > Hi, @akoshchiy , Sorry for the late reply. I don't think it's appropriate to use the `Array(String)` type, because there are both `String` and `Int` types in the key path. We can use the `String` type like PostgreSQL and write a simple parser with [nom](https://docs.rs/nom/latest/nom/) to parse out the key path, which doesn't seem to have complex syntax rules and is relatively easy to write.
> 
> Ok. Simple comma-separated format is enough, isn't it? (e.g. `json_col #> 'a,1,2'`) As I understand, curly braces is a special format for parsing arrays in postgresql.

We'd like to make it easier for users to migrate some of the older SQL by making it compatible with PostgreSQL syntax, and I've implemented a parser for key paths that you can use it directly.  https://github.com/datafuselabs/jsonb/pull/37

**Comment by akoshchiy** [comment]
@b41sh seems that there is a mistake in `@@` description.  Or not?
```
 Extracts JSON Array or Object with JSON path.
```

Postgres reference says that `@@` operator is a equivalent of `jsonb_path_match`.

**Comment by b41sh** [comment]
> @b41sh seems that there is a mistake in `@@` description. Or not?
> 
> ```
>  Extracts JSON Array or Object with JSON path.
> ```
> 
> Postgres reference says that `@@` operator is a equivalent of `jsonb_path_match`.

@akoshchiy  Yes, I made a mistake. Thanks for the correction.

**Comment by b41sh** [comment]
@akoshchiy we've finished all the JSON functions and operators, thanks again for the great work. I found a few more operators in the PostgreSQL docs that could be done, if you're interested, you can continue to work on those!

**Comment by b41sh** [comment]
We've finished all the JSON functions and operators, thanks again to @akoshchiy for your long and excellent work!
