### ISSUE TITLE
Tracking: query profiling framework

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#11874]
Derived from #4238.

To provide a better experience in profiling query performance issues, we will need a framework to record and display the execution info of any specific query.

A profiling library has been proposed in #10023, which will record some execution information and display it via `EXPLAIN ANALYZE` statement.

A system table `query_profile` has been proposed in #11760, which can be used to query the profile information of specific queries with query id.

Further works:
- [ ] Support recording profile information for queries run in cluster mode
- [ ] Support recording table scan profile information
- [ ] GUI tool for displaying the query profile

**Comment by BohuTANG** [comment]
Now:
<img width="871" alt="image" src="https://github.com/datafuselabs/databend/assets/172204/0638b9d2-9210-400f-b617-8a1bdc7a741f">
