### ISSUE TITLE
[Tracking] Refactor SQL layer

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#1217]
To build a robust SQL processing system, it's necessary to divide the components clearly. It is helpful to understand the code.

RFC: https://github.com/datafuselabs/databend/blob/main/website/databend/docs/dev/rfcs/query/0005-new-sql-planner-framework.md

Tracking issue for RFC: #1853 

Tasks:

- [ ] Parser: the component to parse SQL string into AST(Abstract Syntax Tree) #1218 
- [ ] Binder: the component takes AST as input and produce a logical plan https://github.com/datafuselabs/datafuse/issues/1219
- [ ] Optimizer: the component can do some optimization to a logical plan, and eventually produce a nice physical plan
- [ ] Catalog: the component maintains all items in the database(e.g. table, column, index, function), which can help Binder to build a correct logical plan #867 
- [ ] Executor: the component to execute physical plan and produce query result

**Comment by zhang2014** [comment]
Maybe we will follow [it](https://15721.courses.cs.cmu.edu/spring2020/slides/19-optimizer1.pdf):
![image](https://user-images.githubusercontent.com/8087042/127422881-f13afa70-4a94-48ed-ab53-16e52e9c43e7.png)

**Comment by leiysky** [comment]
> Maybe we will follow [it](https://15721.courses.cs.cmu.edu/spring2020/slides/19-optimizer1.pdf):
> ![image](https://user-images.githubusercontent.com/8087042/127422881-f13afa70-4a94-48ed-ab53-16e52e9c43e7.png)

Yes, it's exactly what I mean.

Does the picture come from the lecture of CMU 15-445?

**Comment by zhang2014** [comment]
https://15721.courses.cs.cmu.edu/spring2020/

**Comment by leiysky** [comment]
> > Does the picture come from the lecture of CMU 15-445?
> 
> It from https://15721.courses.cs.cmu.edu/spring2020/

I've followed Andy's coureses for years. 15721 is a nice course which presents the latest academic results and industrial development every year.

**Comment by xudong963** [comment]
> RFC: https://github.com/datafuselabs/databend/blob/master/website/databend/docs/rfcs/query/0005-new-sql-planner-framework.md

404

**Comment by PsiACE** [comment]
> > RFC: https://github.com/datafuselabs/databend/blob/master/website/databend/docs/rfcs/query/0005-new-sql-planner-framework.md
> 
> 404

https://github.com/datafuselabs/databend/blob/main/website/databend/docs/dev/rfcs/query/0005-new-sql-planner-framework.md

**Comment by sandflee** [comment]
https://github.com/datafuselabs/databend/blob/main/website/databend/docs/dev/rfcs/query/0005-new-sql-planner-framework.md is 404 ,  @PsiACE  could you update the latest rfc doc?

**Comment by BohuTANG** [comment]
> https://github.com/datafuselabs/databend/blob/main/website/databend/docs/dev/rfcs/query/0005-new-sql-planner-framework.md is 404 , @PsiACE could you update the latest rfc doc?

Sure, please forward to https://databend.rs/doc/contributing/rfcs/new-sql-planner-framework

**Comment by dusx1981** [comment]
Regarding determining the rules used by Expression, GPORCA's solution is to use bitmaps to manage Rules, and define a RuleFactory to manage all Rules in a unified manner. And classify Rule into Exploration and Implementation. Expression holds a bitmap of the rules that can be applied. When applying a rule, take the bitmap in Expression and all the bitmaps in RuleFactory and to determine the final applied rule, then traverse and apply the rule. After the Exploration stage is completed, all equivalent expressions are generated, and a new tree is generated with Pattern. Is this more efficient?
