### ISSUE TITLE
[Tracking] Refactor SQL Parser

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#1218]
Part of #1217 

## Background
To provide a more generic parser abstraction, we need to do some refactor on the current implementation.

Generally, all of the SQL dialects follow some basic rules, with which we can design our own SQL IR(i.e. datafuse specific AST).

With this IR, we can transform the SQL queries in different dialects into the same representation.

The major idea is provide series of standard AST of Datafuse that can be directly parsed from Datafuse SQL dialect. The elements can be catagorized as:

- `Expression`s, represents expression entries in a SQL query including identifier, arithmetic operators and functions etc.
- `Statement`s, represents SQL clauses, including `SELECT`, `FROM`, `WHERE`, `GROUP BY`, `HAVING`, `ORDER BY`, `LIMIT` and DDL statements.

<del>Beyond this, we can provide interface like `ASTTransformer` to transform AST produced by other parsers(e.g. MySQL, ClickHouse, Postgres) into the standard AST.</del>

### Update: 2021.8.20

We have introduced a series of standard AST API in #1478 .

The main work during this stage is:
- Provide ability to analyze an query with AST(e.g. simple rewrting, expression binding)
- Provide a framework to build logical plan from AST, with normalization.
- Design Datafuse standard SQL #1492  and implement a parser for it (under discussing in #866).

## Tasks

High priority:
- [ ] Implement SQL parser for Datafuse standard SQL #866 
    - [ ] Evaluate SQL dialect framework #1551
- [ ] Standard SQL AST
    - [x] Introduce Datafuse standard SQL AST API @leiysky #1477 
    - [x] Fold table references in FROM clause with CROSS JOIN @leiysky  #1523  
    - [x] Refine object name with qualified typed fields @leiysky #1540
    - [ ] Implement `Visitor` utility for AST @jackwener  #1511 
- [ ] Expression binding and normalization
    - [ ] Bind expression with catalog @leiysky #1537 
    - [ ] Do type check for expressions @leiysky #1538 
    - [ ] Implement rewriter for AST to help normalizing query @leiysky #1539 

Low priority:
- [ ] SQL dialect transformer for ClickHouse SQL
- [ ] SQL dialect transformer for MySQL
- [ ] SQL dialect transformer for Postgres
- [ ] Complete `TransformerSqlparser` @SGZW #1512

**Comment by leiysky** [comment]
Related to #866

**Comment by leiysky** [comment]
I've just filed a PR #1478, which introduces a bunch of Datafuse standard SQL AST and a transformer from `sqlparser-rs`.

Welcome to review and comment.

**Comment by leiysky** [comment]
Closed by #4983

**Comment by sdht0** [comment]
Hi. Coming from the [recent blog post](https://www.databend.com/blog/category-engineering/2025-09-10-query-parser/), this got me curious enough to want to see for myself how much improvement the new parser shows over datafusion-sql. However, the results seem to still be in favor of datafusion-sql:
```
bench                               fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ dummy                                          │               │               │               │         │
   ├─ deep_query_databend           98.09 µs      │ 360 µs        │ 100.7 µs      │ 104.7 µs      │ 100     │ 100
   ├─ deep_query_datafusion         32.12 µs      │ 154.5 µs      │ 32.58 µs      │ 34.06 µs      │ 100     │ 100
   ├─ large_statement_1_databend    71.57 ms      │ 75.09 ms      │ 72.78 ms      │ 72.99 ms      │ 7       │ 7
   ├─ large_statement_1_datafusion  4.316 ms      │ 8.242 ms      │ 4.408 ms      │ 4.534 ms      │ 100     │ 100
   ├─ large_statement_2_databend    1.06 ms       │ 1.424 ms      │ 1.076 ms      │ 1.082 ms      │ 100     │ 100
   ├─ large_statement_2_datafusion  41.7 µs       │ 115.9 µs      │ 42.59 µs      │ 43.58 µs      │ 100     │ 100
   ├─ large_statement_3_databend    1.055 ms      │ 1.127 ms      │ 1.068 ms      │ 1.07 ms       │ 100     │ 100
   ├─ large_statement_3_datafusion  41.6 µs       │ 84.82 µs      │ 42.17 µs      │ 43.4 µs       │ 100     │ 100
   ├─ select_databend               28.17 µs      │ 46.14 µs      │ 28.87 µs      │ 29.17 µs      │ 100     │ 100
   ├─ select_datafusion             2.414 µs      │ 8.687 µs      │ 2.554 µs      │ 2.628 µs      │ 100     │ 100
   ├─ with_select_databend          112.9 µs      │ 160 µs        │ 114.4 µs      │ 115.5 µs      │ 100     │ 100
   ╰─ with_select_datafusion        13.59 µs      │ 37.33 µs      │ 13.89 µs      │ 15.12 µs      │ 100     │ 100
```
The results are after adding a mirror datafusion-sql code to the benchmarks, like so:
```rust
#[divan::bench]
fn select_datafusion() {
    let case = r#"SELECT * FROM my_table WHERE 1 = 1;"#;
    let stmt = Parser::parse_sql(&PostgreSqlDialect {}, case).unwrap();
    divan::black_box(stmt);
}

#[divan::bench]
fn select_databend() {
    let case = r#"SELECT * FROM my_table WHERE 1 = 1;"#;
    let tokens = tokenize_sql(case).unwrap();
    let (stmt, _) = parse_sql(&tokens, Dialect::PostgreSQL).unwrap();
    divan::black_box(stmt);
}
```
Are these results as expected, or am I missing something?

**Comment by bohutang** [comment]
Hi @sdht0 ,

Thank you for reporting this.

Is the benchmark code available on GitHub?

**Comment by sdht0** [comment]
Here's the patch to databend `main`:
```diff
diff --git i/src/query/ast/Cargo.toml w/src/query/ast/Cargo.toml
index e9237ff..2c13dbd 100644
--- i/src/query/ast/Cargo.toml
+++ w/src/query/ast/Cargo.toml
@@ -37,6 +37,7 @@ url = { workspace = true }
 [dev-dependencies]
 divan = { workspace = true }
 goldenfile = { workspace = true }
+sqlparser = "0.59"
 
 [[bench]]
 name = "bench"
diff --git i/src/query/ast/benches/bench.rs w/src/query/ast/benches/bench.rs
index 23ff32d..72e77a4 100644
--- i/src/query/ast/benches/bench.rs
+++ w/src/query/ast/benches/bench.rs
@@ -26,13 +26,130 @@ fn main() {
 
 #[divan::bench_group(max_time = 0.5)]
 mod dummy {
-    use databend_common_ast::parser::parse_expr;
     use databend_common_ast::parser::parse_sql;
     use databend_common_ast::parser::tokenize_sql;
     use databend_common_ast::parser::Dialect;
+    use sqlparser::dialect::PostgreSqlDialect;
+    use sqlparser::parser::Parser;
+
+    const DATAFUSION_DIALECT: PostgreSqlDialect = PostgreSqlDialect {};
 
     #[divan::bench]
-    fn large_statement() {
+    fn select_datafusion() {
+        let case = r#"SELECT * FROM my_table WHERE 1 = 1;"#;
+        let stmt = Parser::parse_sql(&PostgreSqlDialect {}, case).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn select_databend() {
+        let case = r#"SELECT * FROM my_table WHERE 1 = 1;"#;
+        let tokens = tokenize_sql(case).unwrap();
+        let (stmt, _) = parse_sql(&tokens, Dialect::PostgreSQL).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn with_select_datafusion() {
+        let case = "
+            WITH derived AS (
+                SELECT MAX(a) AS max_a,
+                       COUNT(b) AS b_num,
+                       user_id
+                FROM MY_TABLE
+                GROUP BY user_id
+            )
+            SELECT * FROM my_table
+            LEFT JOIN derived USING (user_id)
+        ";
+        let stmt = Parser::parse_sql(&DATAFUSION_DIALECT, case).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn with_select_databend() {
+        let case = "
+            WITH derived AS (
+                SELECT MAX(a) AS max_a,
+                       COUNT(b) AS b_num,
+                       user_id
+                FROM MY_TABLE
+                GROUP BY user_id
+            )
+            SELECT * FROM my_table
+            LEFT JOIN derived USING (user_id)
+        ";
+        let tokens = tokenize_sql(case).unwrap();
+        let (stmt, _) = parse_sql(&tokens, Dialect::PostgreSQL).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn large_statement_1_datafusion() {
+        let case = {
+            let expressions = (0..1000)
+                .map(|n| format!("FN_{n}(COL_{n})"))
+                .collect::<Vec<_>>()
+                .join(", ");
+            let tables = (0..1000)
+                .map(|n| format!("TABLE_{n}"))
+                .collect::<Vec<_>>()
+                .join(" JOIN ");
+            let where_condition = (0..1000)
+                .map(|n| format!("COL_{n} = {n}"))
+                .collect::<Vec<_>>()
+                .join(" OR ");
+            let order_condition = (0..1000)
+                .map(|n| format!("COL_{n} DESC"))
+                .collect::<Vec<_>>()
+                .join(", ");
+
+            format!(
+                "SELECT {expressions} FROM {tables} WHERE {where_condition} ORDER BY {order_condition}"
+            )
+        };
+        let stmt = Parser::parse_sql(&DATAFUSION_DIALECT, &case).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn large_statement_1_databend() {
+        let case = {
+            let expressions = (0..1000)
+                .map(|n| format!("FN_{n}(COL_{n})"))
+                .collect::<Vec<_>>()
+                .join(", ");
+            let tables = (0..1000)
+                .map(|n| format!("TABLE_{n}"))
+                .collect::<Vec<_>>()
+                .join(" JOIN ");
+            let where_condition = (0..1000)
+                .map(|n| format!("COL_{n} = {n}"))
+                .collect::<Vec<_>>()
+                .join(" OR ");
+            let order_condition = (0..1000)
+                .map(|n| format!("COL_{n} DESC"))
+                .collect::<Vec<_>>()
+                .join(", ");
+
+            format!(
+                "SELECT {expressions} FROM {tables} WHERE {where_condition} ORDER BY {order_condition}"
+            )
+        };
+        let tokens = tokenize_sql(&case).unwrap();
+        let (stmt, _) = parse_sql(&tokens, Dialect::PostgreSQL).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn large_statement_2_datafusion() {
+        let case = r#"explain SELECT SUM(count) FROM (SELECT ((((((((((((true)and(true)))or((('614')like('998831')))))or(false)))and((true IN (true, true, (-1014651046 NOT BETWEEN -1098711288 AND -1158262473))))))or((('780820706')=('')))) IS NOT NULL AND ((((((((((true)AND(true)))or((('614')like('998831')))))or(false)))and((true IN (true, true, (-1014651046 NOT BETWEEN -1098711288 AND -1158262473))))))OR((('780820706')=(''))))) ::INT64)as count FROM t0) as res;"#;
+        let stmt = Parser::parse_sql(&DATAFUSION_DIALECT, case).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn large_statement_2_databend() {
         let case = r#"explain SELECT SUM(count) FROM (SELECT ((((((((((((true)and(true)))or((('614')like('998831')))))or(false)))and((true IN (true, true, (-1014651046 NOT BETWEEN -1098711288 AND -1158262473))))))or((('780820706')=('')))) IS NOT NULL AND ((((((((((true)AND(true)))or((('614')like('998831')))))or(false)))and((true IN (true, true, (-1014651046 NOT BETWEEN -1098711288 AND -1158262473))))))OR((('780820706')=(''))))) ::INT64)as count FROM t0) as res;"#;
         let tokens = tokenize_sql(case).unwrap();
         let (stmt, _) = parse_sql(&tokens, Dialect::PostgreSQL).unwrap();
@@ -40,7 +157,14 @@ mod dummy {
     }
 
     #[divan::bench]
-    fn large_query() {
+    fn large_statement_3_datafusion() {
+        let case = r#"SELECT SUM(count) FROM (SELECT ((((((((((((true)and(true)))or((('614')like('998831')))))or(false)))and((true IN (true, true, (-1014651046 NOT BETWEEN -1098711288 AND -1158262473))))))or((('780820706')=('')))) IS NOT NULL AND ((((((((((true)AND(true)))or((('614')like('998831')))))or(false)))and((true IN (true, true, (-1014651046 NOT BETWEEN -1098711288 AND -1158262473))))))OR((('780820706')=(''))))) ::INT64)as count FROM t0) as res;"#;
+        let stmt = Parser::parse_sql(&DATAFUSION_DIALECT, case).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn large_statement_3_databend() {
         let case = r#"SELECT SUM(count) FROM (SELECT ((((((((((((true)and(true)))or((('614')like('998831')))))or(false)))and((true IN (true, true, (-1014651046 NOT BETWEEN -1098711288 AND -1158262473))))))or((('780820706')=('')))) IS NOT NULL AND ((((((((((true)AND(true)))or((('614')like('998831')))))or(false)))and((true IN (true, true, (-1014651046 NOT BETWEEN -1098711288 AND -1158262473))))))OR((('780820706')=(''))))) ::INT64)as count FROM t0) as res;"#;
         let tokens = tokenize_sql(case).unwrap();
         let (stmt, _) = parse_sql(&tokens, Dialect::PostgreSQL).unwrap();
@@ -48,26 +172,17 @@ mod dummy {
     }
 
     #[divan::bench]
-    fn deep_query() {
+    fn deep_query_datafusion() {
+        let case = r#"SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers"#;
+        let stmt = Parser::parse_sql(&DATAFUSION_DIALECT, case).unwrap();
+        divan::black_box(stmt);
+    }
+
+    #[divan::bench]
+    fn deep_query_databend() {
         let case = r#"SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers UNION ALL SELECT * FROM numbers"#;
         let tokens = tokenize_sql(case).unwrap();
         let (stmt, _) = parse_sql(&tokens, Dialect::PostgreSQL).unwrap();
         divan::black_box(stmt);
     }
-
-    #[divan::bench]
-    fn wide_expr() {
-        let case = r#"a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a AND a"#;
-        let tokens = tokenize_sql(case).unwrap();
-        let expr = parse_expr(&tokens, Dialect::PostgreSQL).unwrap();
-        divan::black_box(expr);
-    }
-
-    #[divan::bench]
-    fn deep_function_call() {
-        let case = r#"json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert(json_object_insert('{}'::variant, 'email_address', 'gokul', true), 'home_phone', 12345, true), 'mobile_phone', 345678, true), 'race_code', 'M', true), 'race_desc', 'm', true), 'marital_status_code', 'y', true), 'marital_status_desc', 'yu', true), 'prefix', 'hj', true), 'first_name', 'g', true), 'last_name', 'p', true), 'deceased_date', '2085-05-07', true), 'birth_date', '6789', true), 'middle_name', '89', true), 'middle_initial', '0789', true), 'gender_code', '56789', true), 'gender_desc', 'm', true), 'home_phone_line_type', 'uyt', true), 'mobile_phone_line_type', 4, true)"#;
-        let tokens = tokenize_sql(case).unwrap();
-        let expr = parse_expr(&tokens, Dialect::PostgreSQL).unwrap();
-        divan::black_box(expr);
-    }
 }
```
Run as:
```bash
$ cd src/query/ast/
$ cargo bench      
    Updating crates.io index
     Locking 1 package to latest compatible version
      Adding sqlparser v0.59.0
    Finished `bench` profile [optimized + debuginfo] target(s) in 3.15s
     Running unittests src/lib.rs (databend/target/release/deps/databend_common_ast-e303fbcf64ca662a)

running 14 tests
test ast::statements::workload::tests::test_parse_human_size ... ignored
test ast::statements::workload::tests::test_parse_human_timeout ... ignored
test ast::statements::workload::tests::test_parse_number ... ignored
test ast::statements::workload::tests::test_parse_percentage ... ignored
test parser::error_suggestion::tests::test_context_help ... ignored
test parser::error_suggestion::tests::test_edit_distance ... ignored
test parser::error_suggestion::tests::test_exact_matches ... ignored
test parser::error_suggestion::tests::test_multiple_suggestions ... ignored
test parser::error_suggestion::tests::test_no_suggestions ... ignored
test parser::error_suggestion::tests::test_performance_limits ... ignored
test parser::error_suggestion::tests::test_prefix_matching_accuracy ... ignored
test parser::error_suggestion::tests::test_similarity_scoring ... ignored
test parser::error_suggestion::tests::test_typo_corrections ... ignored
test parser::error_suggestion::tests::test_valid_starts_extraction ... ignored

test result: ok. 0 passed; 0 failed; 14 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running benches/bench.rs (databend/target/release/deps/bench-9ae6ab70084c43ce)
Timer precision: 10 ns
bench                               fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ dummy                                          │               │               │               │         │
   ├─ deep_query_databend           233.8 µs      │ 613.7 µs      │ 242.5 µs      │ 249.7 µs      │ 100     │ 100
   ├─ deep_query_datafusion         37.68 µs      │ 147.6 µs      │ 38.22 µs      │ 39.46 µs      │ 100     │ 100
   ├─ large_statement_1_databend    148.9 ms      │ 152.5 ms      │ 150.6 ms      │ 150.6 ms      │ 4       │ 4
   ├─ large_statement_1_datafusion  4.861 ms      │ 6.246 ms      │ 4.903 ms      │ 4.928 ms      │ 100     │ 100
   ├─ large_statement_2_databend    1.584 ms      │ 1.992 ms      │ 1.6 ms        │ 1.605 ms      │ 100     │ 100
   ├─ large_statement_2_datafusion  45.88 µs      │ 109.6 µs      │ 46.64 µs      │ 47.56 µs      │ 100     │ 100
   ├─ large_statement_3_databend    1.593 ms      │ 2.42 ms       │ 1.613 ms      │ 1.625 ms      │ 100     │ 100
   ├─ large_statement_3_datafusion  45.49 µs      │ 91.96 µs      │ 46.29 µs      │ 47.09 µs      │ 100     │ 100
   ├─ select_databend               60.72 µs      │ 84.36 µs      │ 61.53 µs      │ 62.06 µs      │ 100     │ 100
   ├─ select_datafusion             2.765 µs      │ 10.4 µs       │ 2.855 µs      │ 2.974 µs      │ 100     │ 100
   ├─ with_select_databend          246.4 µs      │ 378.7 µs      │ 252 µs        │ 254.6 µs      │ 100     │ 100
   ╰─ with_select_datafusion        15.49 µs      │ 39.76 µs      │ 15.96 µs      │ 16.32 µs      │ 100     │ 100
```
