### ISSUE TITLE
tracking: implement parquet table using arrow-rs.

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#12245]
**Summary**

- [x] basic read with projection and row_group pruning https://github.com/datafuselabs/databend/pull/12244
- [ ] adaptively choose suitable batch size (too large: OOM; too small: need compact in one thread which is slow) 
    - [x]  internal interface refactor https://github.com/datafuselabs/databend/pull/12309
    - [ ]  more accurate memory estimate for row_group   https://github.com/datafuselabs/databend/pull/12340
- [ ] more tests
- [ ] pruning nested column?
- [ ] page pruning with index

**Comment by Xuanwo** [comment]
Seems iceberg catalog can reuse this feature directly.
