### ISSUE TITLE
Tracking: enhance materialized cte

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#12266]
**Summary**

- [x] support materialized CTE is used in SQL with different aliases
- [x] fix prune column of `CteScan` or `MaterializedCte` operator
- [x] support materialized CTE is used in set operations, such as union
- [x] support materialized CTE is used in [materialized] CTE.
- [x] change tpcds SQLs with `materialized` cte and add them to test suit
