### ISSUE TITLE
Tracking: refactor parquet table.

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#12465]
**Summary**

- [x] Basic refactor of parquet reader. #12424
- [x] Row groups and pages pruning. #12473
- [x] Reading file metas during `read_partitions` to collect stats, check schemas, ... #12569
- [x] Row group level partition. #12569
- [x] Optimize small parquet files reading. #12637
- [x] Introduce Top-K pushdown optimization. #12877
- [x] Specify size for one output block. #12523
- [x] Adjust source parallelism by file sizes and compression ratios. #12637

**Comment by BohuTANG** [comment]
The latest benchmark in Fabric with local parquet TCPH_SF10 parquet files:

<img width="1062" alt="image" src="https://github.com/datafuselabs/databend/assets/172204/427b5b87-75b7-43b2-81f2-8a881fb68f6a">

Q1/Q18/Q19 still have room to improve.

**Comment by RinChanNOWWW** [comment]
The default setting uses `parquet2`. Did this benchmark alter to `parquet_rs`?

**Comment by BohuTANG** [comment]
> The default setting uses `parquet2`. Did this benchmark alter to `parquet_rs`?

This is the notebook code:
```
from databend import SessionContext
ctx_bend = SessionContext("TPCH")
ctx_bend.sql(f"""set use_parquet2=1""").collect()
....
```

**Comment by sundy-li** [comment]
> Q1/Q18/Q19 still have room to improve.

This is not about parquet but query execution.

**Comment by RinChanNOWWW** [comment]
How about `set use_parquet2=0` comparing with `set use_parquet2=1`;

**Comment by BohuTANG** [comment]
Regarding @Dousir9's explanation:

Q1 is related to decimal data type aggregate/groupby.
Q18 is related to join order issue.
Q19 is the filter.

They are not only to parquet file also in fuse engine.

**Comment by BohuTANG** [comment]
> How about `set use_parquet2=0` comparing with `set use_parquet2=1`;

`set use_parquet2=0`:
<img width="1290" alt="image" src="https://github.com/datafuselabs/databend/assets/172204/8c064ba8-8fbf-426d-81ff-3d559ba11741">

**Comment by Dousir9** [comment]
Q1 is also related to aggregation implementation.

**Comment by BohuTANG** [comment]
# The latest version(v1.2.136) benchmark

## set use_parquet2=1
![image](https://github.com/datafuselabs/databend/assets/172204/8823e61a-97ae-48da-bbcc-72eecbc8830c)

## set use_parquet2=0
![image](https://github.com/datafuselabs/databend/assets/172204/85b9995b-5164-480b-ae79-fd90ab4a763e)


It looks good now, cc @RinChanNOWWW @sundy-li  @Dousir9

**Comment by Dousir9** [comment]
> # The latest version(v1.2.136) benchmark
> ## set use_parquet2=1
> ![image](https://user-images.githubusercontent.com/172204/271744734-8823e61a-97ae-48da-bbcc-72eecbc8830c.png)
> 
> ## set use_parquet2=0
> ![image](https://user-images.githubusercontent.com/172204/271745078-85b9995b-5164-480b-ae79-fd90ab4a763e.png)
> 
> It looks good now, cc @RinChanNOWWW @sundy-li @Dousir9

In fact, `set use_parquet2 = 1` is our previous result and `set use_parquet2 = 0` is the new result.

**Comment by BohuTANG** [comment]
> In fact, `set use_parquet2 = 1` is our previous result and `set use_parquet2 = 0` is the new result.

Yes, I think we still have some room to improve the performance of the new parquet.

**Comment by BohuTANG** [comment]
# The latest version(v1.2.148) benchmark: SF25

## set use_parquet2=1
![image](https://github.com/datafuselabs/databend/assets/172204/2cdabc1b-ab55-4a6d-beb8-d9fcc596165e)


## set use_parquet2=0
![image](https://github.com/datafuselabs/databend/assets/172204/66e57a12-b40a-42a0-bb64-235a6041f573)



cc @RinChanNOWWW @sundy-li  @Dousir9

**Comment by BohuTANG** [comment]
# 2023/10/16
# The latest version(v1.2.161) benchmark: SF25

## set use_parquet2=1
![image](https://github.com/datafuselabs/databend/assets/172204/bee8bc93-957b-4eb1-b365-2f57fa4af36e)


## set use_parquet2=0
![image](https://github.com/datafuselabs/databend/assets/172204/2d4cc0a1-6545-42b2-bbb1-d2d919287ae6)




cc @RinChanNOWWW @sundy-li  @Dousir9
