### ISSUE TITLE
Tracking: RBAC improvement plan in 2023 Q4

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#13207]
**Summary**

**Background**

Currently databend have estabilished an working RBAC + DAC system, but there're still some work need to be done to make it more complete.

**Goals**

- cover more privilege checks among uncovered resources, includes:
  - stages
  - warehouses
  - catalog
  - tasks
  - system tables
  - more?
- make a guide for defining privileges
- align the semantics about ownership with snowflake.
- fix the known gotcha about lost privileges after one resource get renamed.

**TODO**

- [x] https://github.com/datafuselabs/databend/issues/13172
- [x] https://github.com/datafuselabs/databend/pull/13537
- [x] https://github.com/datafuselabs/databend/issues/13205
- [x] https://github.com/datafuselabs/databend/issues/13727
- [x] https://github.com/datafuselabs/databend/pull/13852 wait owner control stage and udf.
- [x] #13319
- [x] #13318
- [x] #13440
- [x] #13544
- [x] https://github.com/datafuselabs/databend/issues/13032
- [x] #14148
- [x] #14083
- [x] #14211
- [x] #14209
- [x] #14223
- [x] #13314
- [x] #13777
- [x] #14152
- [x] #14153
- [ ] #13323

next phase:
- [x] #14150
- [x] #14151
- [ ] #13505
- [x] https://github.com/datafuselabs/databend/issues/14261#issue-2069539847
- [x] https://github.com/datafuselabs/databend/issues/14276
- [x] https://github.com/datafuselabs/databend/issues/14279
- [ ] feat: cover privilege check about warehouse
- [ ] feat: cover privilege check about connection
- [x] #14294

**Comment by TCeason** [comment]
Over a period of time, we have ensured permission compatibility and permission override for major objects. It's time for a new journey. Let's tracking RBAC in the new https://github.com/datafuselabs/databend/issues/14618 and close it.
