### ISSUE TITLE
tracking: refactor pipeline builder

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#13573]
**Summary**

- [x] https://github.com/datafuselabs/databend/pull/13571
- [x] https://github.com/datafuselabs/databend/pull/13572
- [x] https://github.com/datafuselabs/databend/pull/13574
- [x] https://github.com/datafuselabs/databend/pull/13575
