### ISSUE TITLE
Tracking: external sort (sort out of core).

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#13889]
**Summary**

The new pipeline will be like:

![sort_ooc eng](https://github.com/datafuselabs/databend/assets/33975039/d553d185-b22e-4d0f-86f7-b5296fef201f)

## Tasks

- [x] Refine distributed sort pipeline in cluster mode. #13881
- [x] Refactor `TransformSortMerge(Limit)` to be able to output data to downstream before finishing. #13927
- [x] Implement a new processor to deal with spilling. #13938
- Improve the sort pipeline with the new processor.
  - [x] Improve the full sort pipeline. #13989
  - [x] Improve the TopN pipeline. #14131
