### ISSUE TITLE
Tracking: Inverted index

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#14825]
**Summary**

- [x] read/write inverted index data
- [ ] add inverted index file locations to meta
- [x] create/drop inverted index
- [ ] filter blocks using inverted index

related to #14505
