### ISSUE TITLE
Tracking: recursive cte

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#15767]
**Summary**

- [ ] basic implementation for recursive cte  (single execution and union all)
- [ ] support union  for recursive cte (union all was supported in 1)
- [ ] reference recursive  cte in multiple places
- [ ] support distributed recursive cte

**Comment by BohuTANG** [comment]
Add: Support window function in recusive CTE

**Comment by xudong963** [comment]
> Add: Support window function in recusive CTE

<img width="916" alt="image" src="https://github.com/datafuselabs/databend/assets/41979257/1d53655c-efb3-47e0-b8cf-be461af1eaa8">

FYI: https://github.com/datafuselabs/databend/blob/main/src/query/sql/src/planner/binder/util.rs#L72-L75
