### ISSUE TITLE
Tracking Issues of Migrating from icelake to iceberg-rust

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#15809]
**Summary**

Years ago, we start [icelake](https://github.com/icelake-io/icelake) to help us integrate with iceberg. Now, our efforts become upstream [iceberg-rust](https://github.com/apache/iceberg-rust).

Iceberg Rust is going to release 0.3, and it has cover all features we needed so far. It's time for us to migrating from icelake to iceberg-rust.

After this migration, we will keep up with the upstream.

## Tasks

- [x] https://github.com/datafuselabs/databend/pull/15844
- [x] https://github.com/datafuselabs/databend/pull/15857
- [x] https://github.com/datafuselabs/databend/pull/15902
- [x] https://github.com/datafuselabs/databend/pull/15906
- [x] https://github.com/datafuselabs/databend/pull/15943
- [x] https://github.com/datafuselabs/databend/pull/15951

**Comment by Xuanwo** [comment]
All tasks have been doen. I'm going to track unfinished tasks in other issues.
