### ISSUE TITLE
tracking: sql variable features

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#16135]
**Summary**

- [x] basic SQL variable support in session level #16134
- [x] IDENTIFIER function support SQL variable   `IDENTIFIER($my_table_name)`, replace ident in NameResolutionContext #16264
- [x] support serde/deserde variables to HTTP response  and apply variables changes during session start (work like settings)
- [x] #16274
- [x] drivers support SQL variables (databend-go, bendsql, databend-jdbc)
- [ ] docs

**Comment by TCeason** [comment]
Got it

**Comment by TCeason** [comment]
Add config or setting about variable quota.

Personally, I'm more biased towards setting. 

Now we has user role quota config. But user and role is a global tenant level object. But var just a session level object.

**Comment by sundy-li** [comment]
> Add config or setting about variable quota.
> 
> Personally, I'm more biased towards setting.
> 
> Now we has user role quota config. But user and role is a global tenant level object. But var just a session level object.

No need now.

**Comment by sundy-li** [comment]
cc @soyeric128  Let's add documents about sql variables.
