### ISSUE TITLE
tracking: memory arbiter

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#16157]
**Summary**

Introduce memory arbiter, when memory exceeds the limit, can perform certain actions to avoid memory overflow.
- Request the caching component to free memory; this will not affect the correctness of the databend query.
- Assess the query that is currently closest to completion(elapsed time / (progress bar * 100) * ((1 - progress bar) * 100)). Allocate all available memory(cache freed memory) resources to it.
- Select the query that is least close to completion and spill it to S3 to free up memory.

**TODO(incomplete)**:

- [ ] Support free memory hook for the data cache.
- [ ] Support spill scheduling logic into the executor.
- [ ] Support the suspension of running queries

**Comment by zhang2014** [comment]
Implemented in workload group.
