### ISSUE TITLE
Feature: Enhancing Stored Procedures

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#16501]
## TODO List for Stored Procedures

- [ ] Implement `Drop procedure if exists`
- [ ] True support for `Create or replace procedure` at the meta layer
- [ ] Error handling for parameter redefinition within `Create Procedure`
- [ ] Dynamic schema adjustment for `Call Procedure`
- [ ] Return type mismatch detection for `Call Procedure`
- [ ] Support `Desc procedure`
- [ ] Support `Alter procedure` (initially focusing on renaming)
- [ ] Allow `Call Procedure` within executable statements
- [ ] Potential introduction of a `resultset` type for better `return table` support
- [ ] Procedure permission management (low priority)
