### ISSUE TITLE
tracking: postgres-compatible number `to_char` function 

### ISSUE THREAD

**Issue by forsaken628** [datafuselabs/databend#16524]
**Summary**
#16480
https://www.postgresql.org/docs/current/functions-formatting.html
- [x] Data type: int8, int16, int32, int64 #16507
- [x] Data type: float, double #16507 
- [ ] Data type: decimal32, decimal64
- [ ] Reuse parsed `FormatNode` 
- [x] Pattern: 9/0/./,/PR/MI/PL/SG/EEEE/literal #16507
- [ ] Pattern: `S` sign anchored to number (uses locale)
- [ ] Pattern: `L` currency symbol (uses locale)
- [ ] Pattern: `D` decimal point (uses locale)
- [ ] Pattern: `G` group separator (uses locale)
- [ ] Pattern: `RN` Roman numeral (input between 1 and 3999)
- [ ] Pattern: `TH` or `th` ordinal number suffix
- [ ] Pattern: `V` shift specified number of digits
- [ ] more test
- [ ] doc

**Comment by AtlasPilotPuppy** [comment]
I would like to take this isue.

**Comment by forsaken628** [comment]
Which part do you intend to implement? @AtlasPilotPuppy

**Comment by AtlasPilotPuppy** [comment]
I have started with the decimal implementation. Since it's my introduction to this code base getting setup took a while.

**Comment by forsaken628** [comment]
https://www.postgresql.org/docs/current/functions-formatting.html#FUNCTIONS-FORMATTING-NUMERIC-TABLE
https://www.postgresql.org/docs/current/locale.html

How far do we have to go to support the locale part of this feature?
