### ISSUE TITLE
[Tracking] Operator updates and integration tests

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1986]
**Summary**

Tasks:

- [ ] Incorporate meta service into operator with security enhancement(TLS certificates, authentication)
- [ ] Simplify and Documenting APIs to let users easy to understand
- [ ] Incorporate operator into CLI cluster profile for cluster life cycle management
- [ ] Integration test (daily) for operator based k8s solution

**Comment by Xuanwo** [comment]
@ZhiHanZ Please transfer this issue to https://github.com/datafuselabs/datafuse-operator insteead.
