### ISSUE TITLE
Summary of improvement about meta and catalog

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2306]
### 
- [ ] Trait `Table` needs a new method `Table::drop` to customize data cleanup.
- [ ] `SledKeySpace` provides universal value type: replace `SledKeySpace::V` to `SledKeySpace::SeqValue<KVValue<V>>`.
- [ ] #2215 
- [ ] Until underlying table storage is ready: #2181 
### Service control
  - [ ] Start up a metasrv cluster. CLI args and docs TODO
### Other:
- [ ] 🤔 anything else?

**Comment by BohuTANG** [comment]
I think this issue ready to close :thinking:

**Comment by drmingdrmer** [comment]
You are right, as always 🤔
