### ISSUE TITLE
[metasrv] Support sled tree level transaction

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#2422]
**Summary**

Support sled tree level transaction for metasrv

**Tasks**
Implementation path:

- [ ] Identify all the codes that need transaction support.
- [x] Define the necessary transaction API and data structures.
- [ ] [[metasrv] make sled support range read](#3309 )
- [ ] Impl a common third-party kv trait that can integrate different kv db.
- [ ] Integrate Rocksdb
- [ ] Test
    - [x] Test when `StateMachine::apply` supports transaction (#3102 )
	- [ ] Test after support sled range read
	- [ ] Change test after we abstract a common kv trait
	- [ ] Test after integrate Rocksdb

**Comment by ariesdevil** [comment]
Implementation path:
1. Identify all the codes that need transaction support.
2. Define the necessary transaction API and data structures.
3. Test.

Current problems
1. sled transaction API does not currently support range operation. (we can bypass it)
2. sled's transaction API is not beautifully designed. (seems the sled author has not worked on it for a long time, we can consider maintaining this project ourselves).

problems ref: https://github.com/spacejam/sled/issues/1143#issuecomment-678115558

**Comment by ariesdevil** [comment]
The transaction API that discussion is look like this:
```rust
struct StateMachine {

    fn apply() {
        self.tree.transaction(|x:view| {
            let ourSledTree = TxnSledTree::from(x)
            let res = self.apply_cmd(ourSledTree, cmd);
            match res {
                // translate to our error code.
            }
        })
    }
}

trait TreeAPI {
    fn get();
    fn insert();
    fn remove();
    fn apply_batch();
}

struct TxnSledTree {

}

impl TreeAPI for TxnSledTree {}

impl TreeAPI for SledTree {}
```

**Comment by drmingdrmer** [comment]
Maybe it is time to have a discussion about what the plan for next move is about this issue?

**Comment by ariesdevil** [comment]
Yup, I'll list the ideal transaction APIs that I want the KV store to have tomorrow, and then we can discuss if we can achieve the goal.

**Comment by jyizheng** [comment]
I guess transaction is needed here because the range scan is not atomic in Bw-tree by design. In other words,  sled (an implementation of bwtree) does not support snapshot isolation, which is very important for analytic queries. The paper below provides a way to implement snapshot isolation for another KV store called Kvell.

https://www.usenix.org/system/files/osdi20-lepers.pdf

The workload might be smaller than implementing a transaction manager from scratch.

**Comment by drmingdrmer** [comment]
@jyizheng 
Thank you man!

**Comment by ariesdevil** [comment]
Some investigation:
1. Bw-tree used by Microsoft also not support the interactive transaction, they use a [transaction component](https://www.snia.org/sites/default/files/SDC15_presentations/database/SudiptaSengupta_Bw-Tree-Key_Value.pdf) for this.
2. CMU Database Group and Intel Labs do much hard work to implement a [bw-tree based store](https://www.cs.cmu.edu/~huanche1/publications/open_bwtree.pdf), but the performance not as high as expected
> In this work, we introduced OpenBw-Tree, our clean slate Bw-Tree
implementation. OpenBw-Tree incorporates a number of optimizations that were not described in the original Bw-Tree papers. Experimental results show that OpenBw-Tree outperforms the original
Bw-Tree design. Nevertheless, even our optimized OpenBw-Tree,
is still considerably slower than other state-of-the-art in-memory
index structures like SkipList, Masstree and ART. OpenBw-Tree is
also slower than a B+Tree that uses optimistic lock coupling, which
indicates that lock-freedom does not always pay off in comparison
with modern lock-based synchronization techniques.

3. Rocksdb support both snapshot isolation and interactive transaction.

cc: @drmingdrmer @jyizheng @BohuTANG

**Comment by ariesdevil** [comment]
As a result, Sled meeting our current needs, although the impl is not so elegant.

**Comment by ariesdevil** [comment]
Some concerns for switching to rocksdb:
1. Rocksdb has too many configs that need more time to learn and tune.
2. Rocksdb is a C++ project, for personal reasons, I don't want a C++ project integrated into our Rust project:)
3. Rocksdb's main goal is to support to Facebook(Meta)'s MyRocks, so many features we don't want to use but if we use rocksdb, we may have to maintain it, at least we need to be familiar with its codes.

**Comment by ariesdevil** [comment]
I think we should list our metasrv roadmap to see if we have more performance and functional requirements, then we can make decisions to switch or not.

**Comment by drmingdrmer** [comment]
https://github.com/spacejam/sled/issues/1390

**Comment by ariesdevil** [comment]
impl #3309

**Comment by drmingdrmer** [comment]
@ariesdevil Let's update status on this issue:DDD

**Comment by ariesdevil** [comment]
We leave an issue(#3309 ) and close this issue now, if you have any ideas, feel free to reopen this issue.
