### ISSUE TITLE
[functions] more functions working with number

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2563]
**Summary**

From MySQL docs in https://dev.mysql.com/doc/refman/8.0/en/numeric-functions.html

Tasks list:

If you are interested in one or more tasks in this issue, you can comment like: `/assignme abs functions` to make this subtask assigned to you, then I'll mark that as wip. 
- [x] add a development doc <how to develop functions in databend>  to guide developers.
- [ ] document of the below functions, refer: https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html
- [x] %, MOD	Modulo operator
- [x] *	Multiplication operator
- [x] +	Addition operator
- [x] -	Minus operator
- [x] -	Change the sign of the argument
- [x] /	Division operator
- [x] ABS()	Return the absolute value [#2596] 
- [x] ACOS()	Return the arc cosine [#2888]
- [x] ASIN()	Return the arc sine [#2888]
- [x] ATAN()	Return the arc tangent [#2888]
- [x] ATAN2(), ATAN()	Return the arc tangent of the two arguments [#2888]
- [x] CEIL()	Return the smallest integer value not less than the argument[#2759]
- [x] CEILING()	Return the smallest integer value not less than the argument[#2759]
- [wip] CONV()	Convert numbers between different number bases
- [x] COS()	Return the cosine [#2610]
- [x] COT()	Return the cotangent [#2610]
- [x] CRC32()	Compute a cyclic redundancy check value [#2616]
- [x] DEGREES()	Convert radians to degrees [#2643]
- [x] DIV	Integer division 
- [x] EXP()	Raise to the power of e [#2847]
- [x] FLOOR()	Return the largest integer value not greater than the argument[#2759]
- [x] LN()	Return the natural logarithm of the argument [#2733]
- [x] LOG()	Return the natural logarithm of the first argument [#2669 ]
- [x] LOG10()	Return the base-10 logarithm of the argument [#2733 ]
- [x] LOG2()	Return the base-2 logarithm of the argument [#2733 ]
- [x] MOD()	Return the remainder [#2850 ]
- [x] PI()	Return the value of pi [#2584]
- [x] POW()	Return the argument raised to the specified power [#2949]
- [x] POWER()	Return the argument raised to the specified power [#2949]
- [x] RADIANS()	Return argument converted to radians [#2643]
- [WIP] RAND()	Return a random floating-point value
- [x] ROUND()	Round the argument [#2923]
- [x] SIGN()	Return the sign of the argument [#2906]
- [x] SIN()	Return the sine of the argument [#2610]
- [x] SQRT()	Return the square root of the argument [#2905 ]
- [x] TAN()	Return the tangent of the argument [#2610]
- [x] TRUNCATE()	Truncate to specified number of decimal places [#2923]

**Comment by flaneur2020** [comment]
```
you can comment like: /assignme abs functions to make this subtask assigned to you.
```

hmm, i tried `/assignme abs functions` but it assigned this issue to me but not the subtask, is this behaviour as expected?

**Comment by BohuTANG** [comment]
> ```
> you can comment like: /assignme abs functions to make this subtask assigned to you.
> ```
> 
> hmm, i tried `/assignme abs functions` but it assigned this issue to me but not the subtask, is this behaviour as expected?

I guess it's OK, @sundy-li will maintain this issue :)

**Comment by Junnplus** [comment]
> PI() Return the value of pi

take this

**Comment by Junnplus** [comment]
hi @sundy-li , Can you update the issue?  CONV DIV RAND is wip, others have been completed.

**Comment by PsiACE** [comment]
> /assignme rand() function

I need to unassign this task for now. Sorry I should manage my task list more sensibly.

also, @Junnplus would you be interested in taking it?

**Comment by mshauneu** [comment]
@PsiACE @sundy-li 
I am working on DIV operator. To finish it I need a help:
- `DIV` operator reqs change of `sqlparser-rs`. So I did it and submit PR (https://github.com/datafuse-extras/sqlparser-rs/pull/9/files) pls take a look...
- impl of `DIV` operator would be simple if databend `/` operator comply with `mysql`, especially for case when delimiter is `0`:
```sql
mysql -uroot -e 'SELECT 1 / 0'
+-------+
| 1 / 0 |
+-------+
|  NULL |
+-------+ 

mysql -h0.0.0.0 -P3307 -uroot -e 'SELECT 1 / 0'
+---------+
| (1 / 0) |
+---------+
|     inf |
+---------+
```
That complicate 'SELECT 1 DIV 0' case much.

I can share my code without support of SELECT 1 DIV 0 for now...with hope databend change `/ 0` in nearest feature.

**Comment by sundy-li** [comment]
@mshauneu  we can have a new function named `intDiv` and map the `div` operator into this function.

For MySQL return NULL if divided by zero, it's related to config `ERROR_FOR_DIVISION_BY_ZERO` in MySQL.  This config will not be introduced in databend, it's too complicated. 

I think it is ok to output `inf`, because  3/0 = 3.0f64/0.0f64 = f64::INFINITY.  Some design of MySQL is poor, no need to be compatible with that.

**Comment by mshauneu** [comment]
@sundy-li *we can have a new function named intDiv and map the div operator into this function* - that is exactly what I am doing right now... The question is what I should return for case `N DIV 0` - returning INF  will lead to return **float** type for any response, that is a bit confusing because DIV assume discard fractional part therefore results could be **int**.

**Comment by Xuanwo** [comment]
@soyeric128 Please take a look at this issue.

**Comment by sundy-li** [comment]
> @soyeric128 Please take a look at this issue.

We will use other issues to track the doc.
