### ISSUE TITLE
FuseStore v0.1 

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#271]
### Roadmap of FuseStore

[project store](https://github.com/datafuselabs/datafuse/projects/21) tracks the detail progress.

- [x] Define metadata types with protobuf. Build an in-memory storage engine, for testing purposes.
- [ ] Setup consensus group to store meta data.
- [x] . . Basic replication logical impl Leader/Follower/NonVoter management.
- [x] . . Apply create database/table action to raft metadata cluster.
- [x] . . #993
- [x] . . . . #775
- [ ] . . test multi candidates cluster and leadership transfer.
- [ ] . . #1125
- [x] . . . . #1117
- [ ] . . Disk backed raft.
- [x] . . . . #1056
- [x] . . . . #1065
- [x] . . . . #1230
- [ ] . . . . #1080
- [ ] . . . . #1081
- [ ] . . . . [store] test: Test: restarting a cluster
- [x] Catalog design @dantengsky
- [ ] . . Flight API @dantengsky
- [ ] Complete the cluster deployment workflow. **PLANNING** @drmingdrmer
- [x] . . #1250
- [ ] . . #1286 @ariesdevil 
- [ ] Store quota and isolation #1127
- [ ] anything else 🤔 ?

**Comment by BohuTANG** [comment]
Add #1127

**Comment by BohuTANG** [comment]
@drmingdrmer this issue maybe should rename or we can close it?

**Comment by drmingdrmer** [comment]
Just close it XDDD

**Comment by drmingdrmer** [comment]
G
