### ISSUE TITLE
Tracking: Support DataType::Decimal

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2931]
**Summary**

Description for this feature.

Now we have introduced Decimal128 and Decimal256 types, let's add more features on decimal types.

- [x] #9894 
- [x] #9856 
- [x] #9926   supports number -> Decimal,  Decimal -> Decimal and arithmetic functions   @sundy-li 
- [x] #10214
- [ ] Group KeysU128 & KeysU256 will be stored as Decimal  @sundy-li 
- [x] #10059 
- [x] #10005
- [x] Add Decimal column stats to segment info (https://github.com/datafuselabs/databend/pull/10113)
- [ ] Decimal literal/encoding @youngsofun 
    - [x] Insert values https://github.com/datafuselabs/databend/pull/10167
         - [x] may fallback to expr of parser
    - [x] Insert/copy with other formats https://github.com/datafuselabs/databend/pull/10176
    - [ ] Cast from string or. allow string directly https://github.com/datafuselabs/databend/pull/10369
    - [x] Used decimal for number literal by default instead of float https://github.com/datafuselabs/databend/issues/10220
    - [x] deal with the float in json.   Float -> string -> decimal. or parse json by ourself
    - [x] binary format used inside.
- [x] #10095 

Below is old comments:

Decimal is Synonymous with Number type.

It represents a range up to 38 digits, with an optional precision and scale:

Precision:
Total number of digits allowed.

Scale:
Number of digits allowed to the right of the decimal point.

By default `Number` means `NUMBER(38,0)` or `Decimal(38, 0)`

|Width | Internal | Size (Bytes) |
|---|---|---|
| 1-4 | INT16 | 2 |
| 5-9 | INT32 | 4 |
| 10-18 | INT64 | 8 |
| 19-38 | INT128 | 16 |

**Comment by liukun4515** [comment]
Hi @sundy-li, I have a question about decimal data type which will be implemented in the feature.
From the [datatype](https://github.com/datafuselabs/databend/blob/f1d0a942dd90ccb91f0949e5c26db94b58e215a1/common/datavalues/src/types/data_type.rs#L26), we know the native data type(i32,i64) is simple. when add the decimal, we need to consider the `precision` and `scale`, refine the data type coercion.

Does the community has the plan to implement it？

**Comment by sundy-li** [comment]
How about making decimal's  physical_type to Int128 ? 
 As arrow did https://github.com/jorgecarleitao/arrow2/blob/main/src/datatypes/mod.rs#L247

**Comment by youngsofun** [comment]
do we need to/ able to support Decimal when check results column types in the sql logical test?

**Comment by sundy-li** [comment]
> do we need to/ able to support Decimal when check results column types in the sql logical test?

Decimal will be formatted into string, so it's same as check string result.

**Comment by BohuTANG** [comment]
@sundy-li 

We also need a task: put the decimal-type column stats to segment to fast pruning.
