### ISSUE TITLE
Tracking issue of use docusaurus to build our website

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3209]
This is a tracking issue of discussion in https://github.com/datafuselabs/databend/discussions/3099

<div type='discussions-op-text'>

<sup>Originally posted by **Xuanwo** November 25, 2021</sup>
Our current website framework is [mkdocs](https://github.com/mkdocs/mkdocs) which is lacking blog support. So I propose to use [docusaurus](https://docusaurus.io/) to build our website.

Docusaurus is maintained by Facebook Opensource, and is widely used (see showcase: https://docusaurus.io/showcase). It's easy to add a new module like `blog` and so on. Also, it has built-in multi-version support, i18n support. And we can extend it via writing a new React module.

More, maybe we can apply for vercel open-source sponsor so that we can deploy on vercel instead of github pages. After that, we can remove the `gh-pages` branch and the `github pages` workflow, we can have a PR preview of our website to avoid broken changes.</div>

## Roadmap

For now, I think there should be three stages:

![image](https://user-images.githubusercontent.com/5351546/144538030-ac9f542f-c12d-412f-9985-eb447f669963.png)

**Current Stage: 2**

### Stage 1

Stage before https://github.com/datafuselabs/databend/pull/3210 gets merged.

At stage 1, we need to:

- [x] Fix markdown format
- [x] Fix social media and resource links (as @PsiACE said)
- [x] Figure out how to use docusaurus and add them into docs.
- [x] Catch up all changes to current docs (**heavy work here**)

### Stage 2

https://github.com/datafuselabs/databend/pull/3210 getting merged means we already changed the databend website framework. However, until we change the `databend.rs` DNS to vercel, this change will not take effect.

- People will still see the site built by MkDocs hosted at `gh-pages`
- All changes to docs will not show up until we get into next stage.

At stage 2, we need to:

- [x] Mirror the current design. https://github.com/datafuselabs/databend/pull/3443
- [x] https://github.com/datafuselabs/databend/issues/3275
- [x] Figure out how to deploy the site
- [x] Only build PR preview while files under `/website` changed (implemented via vercel builtin features)
- [ ] https://github.com/datafuselabs/databend/pull/3585

### Stage 3

The final stage. After DNS is changed, the site will be online and replace the current site.

At stage 3, we need to:

- Have a front-end design (as @BohuTANG said)
- [ ] Write the first blog (maybe?)

## Preview

Take https://databend.vercel.app/ for preview.

**Comment by BohuTANG** [comment]
This looks really cool, we plan it for a long time, thank you @Xuanwo

**Comment by Xuanwo** [comment]
Most docs have been migrated, I need some help to build the home page here (

**Comment by Xuanwo** [comment]
Stage 1 has been finished as #3210 merged, we will focus on stage 2 now.

**Comment by Xuanwo** [comment]
I also create PR #3233 to show the ability of vercel, please take a look. I think it's far more better than plain gh-pages.

**Comment by Xuanwo** [comment]
To address "Figure out how to organize content" in stage 2, I started a new proposal around it: https://github.com/datafuselabs/databend/discussions/3274. Welcome for any comments!

**Comment by juzhiyuan** [comment]
Really cool to use Docusaurus! 😄 

Here is Apache APISIX's Website, and it's also built with Docusaurus since V1 :) 

- https://github.com/apache/apisix-website
- https://apisix.apache.org/

**Comment by Xuanwo** [comment]
> Really cool to use Docusaurus! 😄 
> 
> Here is Apache APISIX's Website, and it's also built with Docusaurus since V1 :) 
> 
> - https://github.com/apache/apisix-website
> - https://apisix.apache.org/

I have learned a lot from APISIX's website,  it's so nice!

**Comment by Xuanwo** [comment]
Thank vercel for sponsoring our documents hosting! We are ready to deploy the new https://databend.rs!

![image](https://user-images.githubusercontent.com/5351546/146700345-b78f6e3a-5186-4110-ad0b-e369ea62a899.png)

**Comment by Xuanwo** [comment]
https://databend.rs/ is online.

Let's close this issue and move to the next stage!

**Comment by juzhiyuan** [comment]
Cool!
