### ISSUE TITLE
Checklist proposal: Nightly v0.7

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3428]
**Summary**

Release name: v0.7-nightly, get in the train now :hand: 

# Checklist

**Stable checklist**
- [x] datafuselabs/databend#2457 
- [x] datafuselabs/databend#3338  
- [x] datafuselabs/databend#3605 
- [x] datafuselabs/databend#3759
- [x] datafuselabs/databend#3906 
- [x] datafuselabs/databend#3206 
- [x]  datafuselabs/databend#4079 

**Experimental checklist**
- [x] datafuselabs/databend#3437 
- [x] datafuselabs/databend#3512 
- [x] datafuselabs/databend#3440 
- [x] datafuselabs/databend#3740 
- [x] datafuselabs/databend#4089
- [x] datafuselabs/databend#3291
- [x] #4242
- [x] datafuselabs/databend#3586 (@BohuTANG )
- [x] #4243
- [x] #4326 (@youngsofun )
- [x] https://github.com/datafuselabs/databend/issues/3792

**Website checklist**
- [x] datafuselabs/databend#3209 

**Testing checklist**
- [ ] datafuselabs/databend#3084 
- [ ] datafuselabs/databend#2647 
- [ ] #3419

# Rolling to next version(Nightly v0.8) checklist
- [ ] datafuselabs/databend#2894 
- [ ] datafuselabs/databend#3004
- [x] datafuselabs/databend#3429
- [ ] datafuselabs/databend#3430
- [ ] datafuselabs/databend#3933 

# Archive releases
- [x] datafuselabs/databend#2525 
- [x] datafuselabs/databend#2257

# Reference
[What's Databend release channels?](https://github.com/datafuselabs/databend/issues/2559)
Nightly v0.7 is part of our [Roadmap 2022](https://github.com/datafuselabs/databend/issues/3706)
Community website: [https://databend.rs](https://databend.rs/)

**Comment by ZhiHanZ** [comment]
I think for test checklist, refactor build system could be done in nightly 0.7 including
1. test framework(https://github.com/datafuselabs/databend/issues/2647)
2. remove unneeded scripts, python, mysql client etc (https://github.com/datafuselabs/databend/discussions/3419)

**Comment by Xuanwo** [comment]
I'm interested to do some refactoring on dal, so that we can:

- https://github.com/datafuselabs/databend/issues/3436
- https://github.com/datafuselabs/databend/issues/3434
- https://github.com/datafuselabs/databend/issues/3435

**Comment by BohuTANG** [comment]
Due to the Chinese Lunar New Year 2022, we will have a delay in this version, happy Chinese new year :tiger: !

**Comment by BohuTANG** [comment]
High Priority Tasks for v0.7 version:

## Query 
- [ ] https://github.com/datafuselabs/databend/issues/3586 (@BohuTANG )


## Storage
- [ ] https://github.com/datafuselabs/databend/issues/4243 (@dantengsky )

## OpenDAL (COPY command needs)
- [ ] https://github.com/datafuselabs/opendal/issues/12 (@Xuanwo )
- [ ] https://github.com/datafuselabs/opendal/issues/54  (@Xuanwo )

**Comment by BohuTANG** [comment]
https://databend.rs/blog/databend-0-7-0-release
