### ISSUE TITLE
Tracking issue of CI Refactor

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3453]
This is the tracking issue of CI Refactor

Proposal: https://github.com/datafuselabs/databend/discussions/3415

## Checklist

- [x] https://github.com/datafuselabs/databend/pull/3344
- [x] Add docs on how our CI works and how to maintain it
- [x] Build on x86_64 looks much slower than other platform?
- [ ] https://github.com/datafuselabs/databend/issues/3611

**Comment by Xuanwo** [comment]
The refactoring has been done. We will continue work on https://github.com/datafuselabs/databend/issues/3611
