### ISSUE TITLE
Copy INTO <table> from external location 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3586]
**Summary**
Load all files in a s3 bucket and insert into table:

```
copy into mytable
  from 's3://mybucket/data/files'
  credentials=(aws_key_id='$AWS_ACCESS_KEY_ID' aws_secret_key='$AWS_SECRET_ACCESS_KEY')
  encryption=(master_key = 'eSxX0jzYfIamtnBKOEOwq80Au6NbSgPH5r4BDDwOaO8=')
  file_format = (type = csv field_delimiter = '|' skip_header = 1);
```

Tasks:
- [x] https://github.com/datafuselabs/databend/pull/4170 (works with minio)
- [x] #4277
- [ ] #4308
- [x] Copy from S3 with Anonymous access (OpenDAL done, TODO: need add a stateful test for it)
- [x] Copy from S3 pattern name files (#4328)
- [x] Copy from S3 all directory files (#4373)
- [x] Copy from with Parquet file (#4373)

**Comment by BohuTANG** [comment]
We need some data accessor apis to help the file reading, maybe we can address it in:
https://github.com/datafuselabs/databend/pull/3575 

cc @Xuanwo

**Comment by Xuanwo** [comment]
I'm working on #3436 now.

I believe we will have a more elegant API design to support those feature requests.

**Comment by GrapeBaBa** [comment]
need wait #3436 ？

**Comment by BohuTANG** [comment]
> need wait #3436 ？

That's right!

**Comment by GrapeBaBa** [comment]
@Xuanwo can this task start right now?

**Comment by Xuanwo** [comment]
@GrapeBaBa, sorry for the late, I think we still need to wait for https://github.com/datafuselabs/databend/issues/3874

**Comment by BohuTANG** [comment]
Plan to experience the new dal design, I take this issue.
Feel free to comments  @GrapeBaBa

**Comment by BohuTANG** [comment]
This feature need openDAL list: https://github.com/datafuselabs/opendal/issues/12 cc @Xuanwo

**Comment by BohuTANG** [comment]
Ready to close, and #4308 rolling to next version(Nightly v0.8)
