### ISSUE TITLE
Tracking issue of Databend Platform Support Policy

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3611]
## Proposal

https://github.com/datafuselabs/databend/discussions/3597

This issue will fix the following issues:

- https://github.com/datafuselabs/databend/issues/3423
- https://github.com/datafuselabs/databend/issues/2063
- https://github.com/datafuselabs/databend/issues/3570

## TODO List

- [ ] Build binaries on ubuntu 18.04/20.04 instead
- [ ] Build statically linked binaries for ubuntu 16.04 or even older distributions
- [ ] Build images for bendctl, databend-query
- [ ] Verify whether our binaries work on macOS.

**Comment by Xuanwo** [comment]
Closing for no progress.
