### ISSUE TITLE
dal2: Implement s3 support

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3774]
Part of https://github.com/datafuselabs/databend/issues/3677

## TODO

- [x] https://github.com/datafuselabs/databend/pull/3775
- [x] https://github.com/datafuselabs/databend/pull/3802
- [x] https://github.com/datafuselabs/databend/pull/3821
- [ ] Add integration tests upon minio

## Waiting

- SDK needs to support path style
- SDK needs to support signature v2

**Comment by Xuanwo** [comment]
not sure if the signature of method `enable_path_style` is composable with the `finish` method, e.g. `builder.enable_path_style().finish()?`

_Originally posted by @dantengsky in https://github.com/datafuselabs/databend/pull/3775#discussion_r778628674_

**Comment by Xuanwo** [comment]
@dantengsky, I think this style works. I will add a test case for `Builder` to make sure they works as expected.
