### ISSUE TITLE
MetaClient and KVClient: resend handshake when handshake info lost

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#3840]
When metasrv restarted, the handshake info is lost. A client in query should resend handshake when such an error occurs.

- [ ] `metasrv` responds an error code indicating there is an unknown handshake info in request meta.
- [ ] KVClient and MetaClient resend handshake if such an error is found.
- [ ] Test: Start metasrv; make a KV/Meta client and send an RPC; restart metasrv; the client should still work correctly.

**Comment by drmingdrmer** [comment]
@ariesdevil Is this issue done?

**Comment by ariesdevil** [comment]
Yup
