### ISSUE TITLE
Todo items for indexes

### ISSUE THREAD

**Issue by zbtzbtzbt** [datafuselabs/databend#4163]
**Summary**

Current we have following three (or four?) indexs in Databend
```
// https://github.com/datafuselabs/databend/blob/main/query/src/storages/index/mod.rs
// mod bloom_filter;
mod index_min_max;
mod index_sparse;
pub mod range_filter;
```

#### Some items we need todo:

- [ ] fulltext index https://github.com/datafuselabs/databend/issues/3915 
- [ ] refactor bloom_filter into datavalues2
- [ ] try different hash algorithm in bloom filter such as fasthash::murmur3(wildly used in redis bloom filter) to find the best hash algo for databend
- [ ] try more indexs such as prefix-index、Z-order-index...

Some ideas may not that useful,feel full to contact me, and i will update this issue.
