### ISSUE TITLE
tracking mysql client auth

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#4351]
- [x] support only mysql_native_password:  databend use double_sha1_password as default when create user, https://github.com/datafuselabs/databend/pull/4352
- [ ] auth_plugin_for_username() current return 'mysql_native_password'.
   - [ ] make in auth_plugin_for_username() in  async, and return error/option, handle it`s error
- [ ] support mysql_clear_password （in progress）
         - [ ]  mysql_clear_password not send scramble
- [ ] support mysql_sha256_password
   - [ ] msql-srv auth interfaces need some change: e.g.  mysql_sha256_password may need another roundtrip to send pubkey to client if client require it.
   - [ ] databend need RSA keys config
- [ ] add docs for auth

interface for msql-srv
---

1.  only support client_plugin mysql_clear_password/mysql_sha256_password/mysql_sha256_password,  msql-srv handle the diff protocol part of them,  impl like databend offer infomations.
    1.  auth_plugin_for_username may return an enum, contain needed information for diff plugin(like keypair for mysql_sha256_password)?  @sundy-li 
2.  like in mysql,  server_plugin can communicate with client directly 

I think the former is enough for most cases
   1. mysql_clear_password can be use for any server_plugin using password
   2. new client_plugin need so in client. we can 

error message for auth type not supported by mysql client (e.g. JWT )
----

2 choices:

1. no additional info, `ERROR 1045 (28000): Access denied for user 'yxf'@'localhost' (using password: YES)`. 
1. tell the client that the user auth type is jwt, must login with http.  which leak the information that ` the user exists`

temp workaround for mysql_sha256_password
---

before mysql_sha256_password  support is done (low priority? need some time to design/review), we can be implemented with mysql_clear_password,  it is not as safe as user expect, but give better user experience before used in production

@wubx

**Comment by sundy-li** [comment]
> auth_plugin_for_username may return an enum, contain needed information for diff plugin(like keypair for mysql_sha256_password)

Great!

**Comment by wubx** [comment]
Never used mysql_clear_password. So I don't want it.
mysql_natve_password work is enough.

**Comment by BohuTANG** [comment]
We have http resetful api, MySQL client is not the main goal, let's close this issue.
