### ISSUE TITLE
Release proposal: Nightly v0.8

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4591]
**Summary**

Release name: v0.8-nightly, get in the train now :hand: 

Milestone: https://github.com/datafuselabs/databend/milestone/1

# Checklist

**Stable checklist**
- [x] Query(Copy): #4584
- [x] Query(Copy): https://github.com/datafuselabs/databend/issues/4527
- [x] Query(Copy):  https://github.com/datafuselabs/databend/issues/4498
- [x] Query(Copy):  https://github.com/datafuselabs/databend/issues/4308
- [x] Query(Insert): https://github.com/datafuselabs/databend/issues/4577
- [x] Query(View): https://github.com/datafuselabs/databend/issues/4610
- [x] Query(Insert): #4413  
- [x] Query(SQL):https://github.com/datafuselabs/databend/issues/4877
- [x] Query (TimeZone): #4651  
- [x] Query(DataType): https://github.com/datafuselabs/databend/issues/3916
- [x] Query(information_schema): https://github.com/datafuselabs/databend/issues/4659
- [x] Query(DataType): https://github.com/datafuselabs/databend/issues/4874
- [x] Query(ALTER): #4839
- [x] Query(DML): https://github.com/datafuselabs/databend/pull/4757
- [x] Query(DML) https://github.com/datafuselabs/databend/pull/4532 
- [x] Query(DataType): [Support Array\<T\> Data Type](https://github.com/datafuselabs/databend/pull/5049)
- [x] Query(Function): #5073 
- [x] Query(Function): https://github.com/datafuselabs/databend/pull/4970 
- [x] Query(Function): https://github.com/datafuselabs/databend/pull/4944
- [x] Query(Function): https://github.com/datafuselabs/databend/pull/4771
- [x] Query(Function): https://github.com/datafuselabs/databend/pull/4684  
- [x] Query(Function) : https://github.com/datafuselabs/databend/pull/4534
- [x] Query(Source): https://github.com/datafuselabs/databend/pull/4561
- [x] Query(Settings): https://github.com/datafuselabs/databend/pull/6579
- [x] Query(Handler): https://github.com/datafuselabs/databend/pull/7012
- [x] Query(Planner): https://github.com/datafuselabs/databend/issues/6246
- [x] Storage(Delete): https://github.com/datafuselabs/databend/issues/5691
- [x] Storage(Azblob): https://github.com/datafuselabs/databend/pull/5025
- [x] Storage(TimeTravel): https://github.com/datafuselabs/databend/pull/5562
- [x] Storage(clustering_information): https://github.com/datafuselabs/databend/pull/5426
- [x] Storage(Index): https://github.com/datafuselabs/databend/pull/6639
- [x] Cloud(User): datafuselabs/databend#2894 
- [x] Executor(Processor): https://github.com/datafuselabs/databend/issues/4646
- [x] API(REST): https://github.com/datafuselabs/databend/issues/4568
- [x] API(JDBC): https://github.com/datafuselabs/databend/issues/4581
- [x] Query(Optimizer): https://github.com/datafuselabs/databend/issues/7069
- [x] Storage(predict): #7078 
- [x] Query(SQL): https://github.com/datafuselabs/databend/issues/514

**Experimental checklist**
- [x] Planner: https://github.com/datafuselabs/databend/issues/3747
- [x] Query(UDF): https://github.com/datafuselabs/databend/issues/3994
- [x] Query(GroupBy): https://github.com/datafuselabs/databend/issues/4602
- [x] Storage(ClusterKey): https://github.com/datafuselabs/databend/issues/4268
- [x] Storage(COPY): https://github.com/datafuselabs/databend/issues/5380
- [x] Storage(External): https://github.com/datafuselabs/databend/issues/4826
- [x] Meta: https://github.com/datafuselabs/databend/issues/4393
- [x] Meta: https://github.com/datafuselabs/databend/issues/4312
- [x] OpenDAL: https://github.com/datafuselabs/opendal/issues/70

**Testing checklist**
- [x] datafuselabs/databend#3084 

**Move to the next release([v0.9](https://github.com/datafuselabs/databend/issues/7052))**
- [ ] Query(Cache): https://github.com/datafuselabs/databend/issues/4521
- [ ] Executor(Processor): https://github.com/datafuselabs/databend/issues/4238
- [ ] Storage(Table): https://github.com/datafuselabs/databend/issues/3461
- [ ] Query(AZBLOB): https://github.com/datafuselabs/databend/issues/5314

# Archive releases
- [x] datafuselabs/databend#3428 
- [x] datafuselabs/databend#2525 
- [x] datafuselabs/databend#2257

# Reference
[What are Databend release channels?](https://github.com/datafuselabs/databend/issues/2559)
Nightly v0.8 is part of our [Roadmap 2022](https://github.com/datafuselabs/databend/issues/3706)
Community website: [https://databend.rs](https://databend.rs/)

**Comment by BohuTANG** [comment]
Add:
Query(information_schema) @issue-4659

**Comment by Xuanwo** [comment]
Released at: https://github.com/datafuselabs/databend/releases/tag/v0.8.0-nightly

Thanks for everyone!

**Comment by Xuanwo** [comment]
Released at: https://github.com/datafuselabs/databend/releases/tag/v0.8.0-nightly

Thanks for everyone!
