### ISSUE TITLE
Tracking issues of adopting features added in OpenDAL v0.5

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#4736]
OpenDAL v0.5 added the following features

- Azblob
- Create dir
- Decompress read

> Read [OpenDAL v0.5 Release](https://github.com/datafuselabs/opendal/discussions/233) for more information

This issue intends to track the adoption of OpenDAL v0.5:

- [x] #4738
- [x] #4739
- [x] #5380
- [x] Code cleanup for `object("abc/").write(vec![])` trick
- [x] https://github.com/datafuselabs/databend/issues/4449
- [x] Code Cleanup: https://github.com/datafuselabs/databend/pull/5251
- [x] Code Cleanup: https://github.com/datafuselabs/databend/pull/5280

**Comment by Xuanwo** [comment]
To support azblob, we need some refactoring on our config, I'm working on https://github.com/datafuselabs/databend/issues/4362

**Comment by Xuanwo** [comment]
https://github.com/datafuselabs/databend/pull/5655 adds decompress read supports!
