### ISSUE TITLE
tracking sharing

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#4814]
[StateMachine](https://github.com/datafuselabs/databend/blob/0278dfd3514cd63f38d05bbfa4768ab046fd496e/common/meta/raft-store/src/state_machine/sm.rs#L379) key spaces:

1. shares/g_share_id -> share_info(name, option<db_name>, tables)
  1.   tables may use seperate key space when the designe is stable
2. share_lookup/provider/share_name -> g_share_id 
3. share_outbunds/g_share_id/consumer -> share_outbund_meta(created_on)
4. share_inbunds/consumer/g_share_id->  share_inbund_meta(created_on, option<database_name>)
5. databases /db_id ->  db_meta  ##  engine_option.share_id = g_share_id

add meta_api:
- [x] create/drop shares
- [ ] grant/revoke share to tenant
- [ ] grant/revoke privileges to share
- [ ] get share_ext (and more tests for)

 

affected api
- [ ] create/drop database from share
- [ ] get_tables 
- [ ] get_table
- [ ] grant privilege to user/role

SQLs:

- [ ] create/drop share
- [ ] grant/revoke privilige to share
- [ ] grant/revoke share to tenant
- [ ] create/drop database 'db_1' engine='share'（share='tenant_A'.'share_1'）
- [ ] desc share
- [ ] show shares

read 

- [ ] shared table with storage conf

tests:

- [ ] unit test

**Comment by xudong963** [comment]
SM means storage meta? @youngsofun

**Comment by youngsofun** [comment]
state machine @xudong963
