### ISSUE TITLE
Tracking issue: table cluster key

### ISSUE THREAD

**Issue by zhyass** [datafuselabs/databend#4946]
Cluster key is to organize the storage of data to better suit expected queries. The goals are to improve query performance whilst reducing the system resources required to execute queries.

#4268 

## clustering
- [x] https://github.com/datafuselabs/databend/issues/6857
- [x] https://github.com/datafuselabs/databend/pull/5194
- [x] https://github.com/datafuselabs/databend/issues/5473

## syntax
- [x] https://github.com/datafuselabs/databend/pull/4999
- [x] https://github.com/datafuselabs/databend/pull/5718
- [x] https://github.com/datafuselabs/databend/pull/5835
- [x] https://github.com/datafuselabs/databend/pull/5426

## task
- [x] https://github.com/datafuselabs/databend/issues/5861
~~- [ ] https://github.com/datafuselabs/databend/issues/5326~~

**Comment by Xuanwo** [comment]
All tasks have been finished. Let's close.
