### ISSUE TITLE
Make meta type struct more flex for serializing

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4962]
**Summary**

https://github.com/datafuselabs/databend/tree/301a3d7add6ea915a300f18aa5c2b128e2e8406c/common/meta/types/src

- [ ] Add new meta types with serde
- [ ] Add alias for each filed
- [ ] Add defaut for each field

**Comment by BohuTANG** [comment]
Plan to use protobuf for serializing, so no need serde, closed.
