### ISSUE TITLE
Tracking issues of adopting features added in OpenDAL v0.6

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#5215]
OpenDAL v0.6 added the following features

- retry able operations
- hdfs services support

> Read [OpenDAL v0.6 Release](https://github.com/datafuselabs/opendal/discussions/265) for more information

This issue intends to track the adoption of OpenDAL v0.6:

- [x] https://github.com/datafuselabs/databend/pull/5216
- [x] https://github.com/datafuselabs/databend/pull/5245
- [x] https://github.com/datafuselabs/databend/pull/5247
