### ISSUE TITLE
Tracking issue of RFC Config Backward Compatibility

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#5297]
## Background

There should be a `ver` to identify the `proto-conv` version if this message has chances to be used alone. Otherwise, without a `ver`, it implies `proto-conv` will always have to be able to deal with any old version `S3StorageConfig` message.

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/databend/pull/5280#discussion_r869913827_

## RFC

[Config Backward Compatibility](https://github.com/datafuselabs/databend/blob/4aab38cc0ab46a3f718788d402ef53554c62f2c3/docs/doc/60-contributing/03-rfcs/20220512-config-backward-compatibility.md)

## Roadmap

- [x] https://github.com/datafuselabs/databend/pull/5324
- [x] https://github.com/datafuselabs/databend/pull/5399
- [x] https://github.com/datafuselabs/databend/pull/5409
- [x] https://github.com/datafuselabs/databend/pull/5421
- [x] Add tests for both inner and outer config
- [x] Add detailed docs for config maintain

## Unresolved Problems

- serde alias may not work as expected, we need to handle the backward compatibility by hand

**Comment by Xuanwo** [comment]
Most work have been done. Let's close.
