### ISSUE TITLE
Tracking issue of result cache and download

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#5398]
**Summary**

background
-----

Originally posted by @BohuTANG  in https://github.com/datafuselabs/databend/issues/4521

`result table` is used in multi places:

- downloading with formats
- table function like [result_scan(<query_id>)](https://docs.snowflake.com/en/sql-reference/functions/result_scan.html)
- internal cache for other queries.  see  https://github.com/datafuselabs/databend/issues/4521

Roadmap
----

- [x] able to download result base on `result table` https://github.com/datafuselabs/databend/pull/5395
    - [x] write to `result table` when serving `/v1/query`
    - [x] read `result table` to  to serve `/v1/query/<query_id>/download
    - [x] use `result table`  to make `/v1/query`  not blocked by client due to limited memory buffer
- [ ] support more download format
- [ ] management of `result table`,  delete outdated 
- [ ] use table function to read it    `from table(result_scan(last_query_id()))`
- [ ] optimize write pipeline with 2 sinks
- [ ] clickhouse/mysql write to `result table` too.
- [ ] use `result table` to optimize query
- [ ] avoid huge result  https://github.com/datafuselabs/databend/issues/5398#issuecomment-1127550180
- [ ] download without bendquery，

optional：

- [ ] download limit rows，
- [ ] download parallel

**Comment by BohuTANG** [comment]
If `select * from a huge table`(with TB data size), we should reject the result cache.
