### ISSUE TITLE
Tracking issue of i18n support of databend.rs

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#5542]
I will track the progress of i18n support of databend.rs

In general, we will adopt the features provided by [docusaurus: i18n - Introduction](https://docusaurus.io/docs/next/i18n/introduction) and [crowdin](https://databend.crowdin.com/).

In this workflow, we will:

- Upload all text that needs to be translated (by crowdin)
- Translate text in `crowdin`
- Commit back to databend (by crowdin)

## Current status

- Databend's Crowdin Org: https://databend.crowdin.com/ (sign up via github)

## Checklist

- [ ] Setup crowdin and apply for open project sponsor.
- [ ] Integrate to crowdin via github actions (https://support.crowdin.com/enterprise/github-crowdin-action/)
- [x] https://github.com/datafuselabs/databend/pull/5545
- [x] https://github.com/datafuselabs/databend/pull/5546

**Comment by Xuanwo** [comment]
Basic support added, let's start i18n!
