### ISSUE TITLE
Tracking issue of RFC User-friendly Release

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#5681]
**Motivation**

In the past, only specific binaries were included in the Databend release. Understanding how to operate and maintain Databend often requires extensive discussion.

This proposal aims to improve this process by providing some simple tips and default configs to help make the process painless for users.

**RFC**

[User-friendly Release](https://databend.rs/doc/contributing/rfcs/user-friendly-releases)

**Roadmap**

- [ ] add more comments to the configuration files
- [ ] write a readme.txt
- [ ] update the release workflow
