### ISSUE TITLE
Tracking issue for adding cluster-name to metasrv

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#5743]
The following task to enable cluster-name check:

- [ ] The implementation of `RaftNetwork` has to send cluster-name in every request.
- [ ] Raft RPC handler has to check the cluster-name before handling an RPC.
- [ ] Non-raft RPC should send cluster-name to the remote peer too.
- [ ] Non-raft RPC has to check the cluster-name before handling an PRC.

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/databend/issues/5740#issuecomment-1144515628_
