### ISSUE TITLE
Compatibility support: metasrv on-disk data

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#5881]
Metasrv has to provide backward/forward compatibility to its on-disk data:

An old metasrv should be able to load data written by a new metasrv.
A new metasrv should be able to load data written by an old metasrv.

- [ ] Add compatibility test, similar to `tests/compat/test-compat.sh`: download minimal compatible metasrv; Generate data with new metasrv, bring up an old metasrv; Generate data with old metasrv, bring up a new metasrv.
- [ ] `metasrv` has to maintain a min-compatible data version, similar to `MIN_METACLI_SEMVER`.
- [ ] `metasrv --cmd ver` outputs the min-compatible data version.
- [ ] TODO: consider writing the version of metasrv to its on-disk data folder. When a new version is written, all old data has to be converted to new version format.
