### ISSUE TITLE
Refactor common-ast into more readable way

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6211]
This issue is used to track the refactor on `common-ast`.

I plan to refactor `common-ast` into more readable way with the following changes:

- Make sure the statement along with its parser, so we don't need to jump to different files for debugging
- Implement unit tests for statement parser so we can test a single part of ast (For example, `comma_separated_list1` and `copy_target`)
- Expose items instead of internal modules.

Finally, we can move `common-ast` out of databend so that the rust community can re-use our parser for integration or check.

## Todo List

- [x] https://github.com/datafuselabs/databend/pull/6210
- [x] Split `parser::statement` into `ast::statements`
- [ ] Renaming to `common-sql-parser`
  - As advised by @leiysky

---

ping @leiysky @andylokandy @xudong963 for ideas.

**Comment by leiysky** [comment]
By the way, I suggest to rename `common-ast` to `common-sql-parser`.

**Comment by xudong963** [comment]
> Finally, we can move `common-ast` out of databend so that the rust community can re-use our parser for integration or check.

Nice, I've thought about doing this before！ Seems there is no one ergonomic parser in rust community

**Comment by andylokandy** [comment]
> Finally, we can move common-ast out of databend so that the rust community can re-use our parser for integration or check.

I'm wondering if it it ok to have databend-specific statements in such a community crate tho...

**Comment by Xuanwo** [comment]
Most work has been down. The crate renaming will happen after old planner removed.
