### ISSUE TITLE
Tracking: window function

### ISSUE THREAD

**Issue by fkuner** [datafuselabs/databend#6342]
**Summary**

migrate window function to new planner

- [x] window function parser #10430
- [ ] window function binder & planner
- [ ] essential window support in aggregate function & WindowTransform
- [ ] more window operators (rank, dense_rank ...)

Optional:
1. segment tree of aggregate state
2. incrementable state

Reference:

- http://www.vldb.org/pvldb/vol8/p1058-leis.pdf  
- [Windowing in DuckDB - DuckDB](https://duckdb.org/2021/10/13/windowing.html)
- http://www.vldb.org/pvldb/vol9/p1221-wesley.pdf

**Comment by youngsofun** [comment]
@fkuner are you work on this issue? may I take it?
