### ISSUE TITLE
Tracking issue of proposal: Semantic Release

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6384]
- https://github.com/datafuselabs/databend/discussions/6383

## Todo List

- [x] https://github.com/datafuselabs/databend/pull/6386
- [x] Enable semantic releases via github releases
- [x] Change our release actions
- [x] Add post check for better experience https://docs.mergify.com/actions/post_check/
  
![image](https://user-images.githubusercontent.com/5351546/176861230-653ed5c1-081f-457e-a505-b68655acd3d7.png)

**Comment by Xuanwo** [comment]
We don't need to push a tag for releasing, we can create a release directly, github will create tag for us.

**Comment by Xuanwo** [comment]
![image](https://user-images.githubusercontent.com/5351546/177068544-d7392aad-10ca-4149-9105-c76009b5108a.png)

**Comment by Xuanwo** [comment]
All tasks have been done, closing!
