### ISSUE TITLE
Tracking: geo h3 functions

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#6390]
**Summary**
Support Geography functions

Implemented:
* [x] h3_is_valid
* [x] h3_get_resolution
* [x] h3_edge_length_m
* [x] h3_edge_length_km
* [x] geo_to_h3 
* [x] h3_to_geo
* [x] h3_to_geo_boundary
* [x] h3_k_ring
* [x] h3_get_base_cell
* [x] h3_hex_area_m2
* [x] h3_hex_area_km2
* [x] h3_indexes_are_neighbors
* [x] h3_to_children
* [x] h3_to_parent
* [x] h3_to_string
* [x] string_to_h3
* [x] h3_is_res_class_iii
* [x] h3_is_pentagon
* [x] h3_get_faces
* [x] h3_cell_area_m2
* [x] h3_cell_area_rads2
* [x] h3_get_resolution
* [x] h3_to_center_child
* [x] h3_exact_edge_length_m
* [x] h3_exact_edge_length_km
* [x] h3_exact_edge_length_rads
* [x] h3_num_hexagons
* [x] h3_line
* [x] h3_distance
* [x] h3_hex_ring
* [x] h3_get_unidirectional_edge
* [x] h3_edge_angle
* [x] h3_unidirectional_edge_is_valid
* [x] h3_get_origin_index_from_unidirectional_edge
* [x] h3_get_destination_index_from_unidirectional_edge
* [x] h3_get_indexes_from_unidirectional_edge
* [x] h3_get_unidirectional_edges_from_hexagon
* [x] h3_get_unidirectional_edge_boundary

Not implemented:

**Comment by infdahai** [comment]
I'd like to finish  the `intersect_count` function.

**Comment by nange** [comment]
I'll continue to take: `h3IsValid`, `h3GetResolution`, `h3EdgeLengthM`, `h3EdgeLengthKm`.

**Comment by nange** [comment]
I'll contine to take: `h3GetBaseCell`, `h3HexAreaM2`, `h3HexAreaKm2`, `h3IndexesAreNeighbors`, `h3ToChildren`, `h3ToParent`.

**Comment by nange** [comment]
I'll continue to take: `h3ToString`, `stringToH3`, `h3IsResClassIII`,  `h3IsPentagon`,  `h3GetFaces`,  `h3CellAreaM2`, `h3CellAreaRads2` .

**Comment by nange** [comment]
I'll continue to take:  `h3_to_center_child`, `h3_exact_edge_length_m`, `h3_exact_edge_length_km`, ` h3_exact_edge_length_rads`, `h3_num_hexagons`, `h3_line`, `h3_distance`, `h3_hex_ring`, `h3_get_unidirectional_edge`.

**Comment by nange** [comment]
Hi @ariesdevil , I didn't find out the document about `h3_edge_angle`. Could you please provide a Ref or more infomation?

**Comment by ariesdevil** [comment]
@nange https://clickhouse.com/docs/en/sql-reference/functions/geo/h3#h3edgeangle

**Comment by ariesdevil** [comment]
close with https://github.com/datafuselabs/databend/pull/12456
