### ISSUE TITLE
[Tracking] Improve Hive Engine Performance

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6613]
**Summary**

Description for this feature.

I think there are three main tasks that we can do to improve the performance of hive engine.

- [ ] Metadata cache during reading partition.
- [ ] Predict push down during reading parquet files.
- [ ] Partition pruner for Partitioned table (currently we don't support partitioned table, so it's in low-priority).

cc @dantengsky  @sandflee

**Comment by sandflee** [comment]
https://github.com/datafuselabs/databend/issues/6123 also tracks some works to do for hive query, including foundamental issues（such as read more than one rowgroup，support more column types） and performance ones， we’re doing the foundamental issues。

**Comment by sundy-li** [comment]
Ok, let's close it and migrate to issue #6123
