### ISSUE TITLE
Enable new planner by default

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6644]
**Summary**

Description for this feature.

- [x] enable database, tables related DDL statements to new planner by default #6648 
- [x] enable show statements to new planner by default #6648 
- [x] enable copy/list statements to new planner by default #6648 
- [x] enable user/roles statements to new planner by default  #6687 
- [x] enable undrop/delete  statements to new planner by default  #6716 
- [ ] ~enable global setting to new planner by default~ (work in new planner)
- [ ] enable insert/explain/select statement to new planner by default
- [x] https://github.com/datafuselabs/databend/issues/6683

**Comment by Xuanwo** [comment]
cc @sundy-li, I will take part in https://github.com/datafuselabs/databend/issues/6683

**Comment by sundy-li** [comment]
> cc @sundy-li, I will take part in #6683

Ok, you can start it after #6648 is merged.

**Comment by BohuTANG** [comment]
Add `enable the global setting to the new planner by default` task to the list, cc @sundy-li 
Reference https://github.com/datafuselabs/databend/pull/6579

**Comment by sundy-li** [comment]
> Add `enable the global setting to the new planner by default` task to the list, cc @sundy-li Reference #6579

We can set global using:

```
set enable_planner_v2 = 1;
set gloabl enable_planner_v2 = 1;
```

Then:
```
➜ mysql -h 127.0.0.1  -P3307 -uroot --prompt "databend > "
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 39
Server version: 8.0.26-v0.7.137-nightly-98ec93e-simd(rust-1.64.0-nightly-2022-07-26T01:41:27.160938502Z) 0

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

databend > explain select sum(number) from numbers(100);
+-------------------------------------------------------------------------------------------+
| explain                                                                                   |
+-------------------------------------------------------------------------------------------+
| Project: [sum(number)]                                                                    |
| └── EvalScalar: [sum(number)]                                                             |
|     └── Aggregate(Final): group items: [], aggregate functions: [sum(number)]             |
|         └── Aggregate(Partial): group items: [], aggregate functions: [sum(number)]       |
|             └── Scan: default.system.numbers                                              |
+-------------------------------------------------------------------------------------------+
5 rows in set (0.041 sec)
```

**Comment by BohuTANG** [comment]
Cloud platform can not do 'set enable_planner_v2 = 1'
