### ISSUE TITLE
Track: Sql logic test experience improvement

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#6699]
### Summary

This is a tracking issue for sql logic experience, anything about logic test can put here.

### tasks

- [x]  https://github.com/datafuselabs/databend/issues/6696
- [x]  https://github.com/datafuselabs/databend/issues/6694
- [x]  https://github.com/datafuselabs/databend/issues/6697
- [x] https://github.com/datafuselabs/databend/issues/6701
- [x] https://github.com/datafuselabs/databend/issues/6705
- [x] https://github.com/datafuselabs/databend/issues/6709
- [x] https://github.com/datafuselabs/databend/issues/7027

**Comment by Xuanwo** [comment]
Great tracking issue!

**Comment by ZeaLoVe** [comment]
1. Column name check support
2. Regular match column results, especially time.

**Comment by Xuanwo** [comment]
All issues resolved. Let's close!
