### ISSUE TITLE
Migrate `String` functions to new expression framework

### ISSUE THREAD

**Issue by andylokandy** [datafuselabs/databend#6766]
# Tasks

Legacy string functions are settle in `common/functions/src/scalars/strings`. The task is to migrate all of them to `common/functions-v2/src/scalars/string.rs`. Similarly, the legacy tests in `common/functions/tests/it/scalars/strings` should also be migrated to `common/functions-v2/tests/it/scalars/string.rs`.

- [x] #6770
- [x] #6771
- [x] `rtrim` https://github.com/datafuselabs/databend/pull/6921
- [x] `trim` https://github.com/datafuselabs/databend/pull/6921
- [x] `trim_leading` https://github.com/datafuselabs/databend/pull/6921
- [x] `trim_trailing` https://github.com/datafuselabs/databend/pull/6921
- [x] `trim_both` https://github.com/datafuselabs/databend/pull/6921
- [x] `ltrim` https://github.com/datafuselabs/databend/pull/6921
- [x] `quote` https://github.com/datafuselabs/databend/pull/6907
- [x]  `lower` https://github.com/datafuselabs/databend/pull/6775
- [x] `lcase` https://github.com/datafuselabs/databend/pull/6775
- [x] `upper` #6765
- [x] `ucase` #6765
- [x] `reverse` https://github.com/datafuselabs/databend/pull/6907
- [x] `soundex` https://github.com/datafuselabs/databend/pull/7539
- [x] `ascii` https://github.com/datafuselabs/databend/pull/6907
- [x] #6776
- [x] #6777
- [x] #6778
- [x] #6779
- [x] `ord` https://github.com/datafuselabs/databend/pull/7539
- [x] `regexp_instr` https://github.com/datafuselabs/databend/pull/7459
- [x] `regexp_like` https://github.com/datafuselabs/databend/pull/7459
- [x] `regexp_replace` https://github.com/datafuselabs/databend/pull/7459
- [x] `regexp_substr` https://github.com/datafuselabs/databend/pull/7459
- [x] `bin` https://github.com/datafuselabs/databend/pull/7219
- [x] `oct` https://github.com/datafuselabs/databend/pull/7219
- [x] `hex` https://github.com/datafuselabs/databend/pull/7219
- [x] `unhex` https://github.com/datafuselabs/databend/pull/7219
- [x] `repeat` https://github.com/datafuselabs/databend/pull/7571
- [x] `substring` https://github.com/datafuselabs/databend/pull/7583
- [x] `mid` https://github.com/datafuselabs/databend/pull/7583
- [x] `substr` https://github.com/datafuselabs/databend/pull/7583
- [x] `left`https://github.com/datafuselabs/databend/pull/7583
- [x] `right`https://github.com/datafuselabs/databend/pull/7583
- [x] `concat` https://github.com/datafuselabs/databend/pull/7167
- [x] `concat_ws` https://github.com/datafuselabs/databend/pull/7167
- [x] `space` https://github.com/datafuselabs/databend/pull/7583
- [x] `lpad`
- [x] `rpad`
- [x] `char` https://github.com/datafuselabs/databend/pull/7539
- [x] `insert` #7564
- [x] `replace`
- [x] `strcmp`
- [x] `locate`， POSITION(substr IN str) is a synonym for LOCATE(substr,str).
- [x] `instr` alias `locate`

Lower priority, not commonly used, could be deprecated:
- [ ] `elt`
- [ ] `export_set`
- [ ] `find_in_set`
- [ ] `field`
- [ ] `substring_index`
- [ ] `format`

Tracked in https://github.com/datafuselabs/databend/issues/6547

**Comment by ygf11** [comment]
hi @andylokandy. I can migrate some functions.

`to_base64` and `from_base64` looks simple, let me start them first.

**Comment by PsiACE** [comment]
> `to_base64` and `from_base64` look simple, let me start them first.

You can comment on these two issues and I will assign them to you

- `to_base64` #6770 
- `from_base64` #6771

**Comment by andylokandy** [comment]
Since there are too many functions here, and also because we may implement many of them in one PR, I propose not to open sub-issues and instead just leave a comment here to state which tasks you'd like to work on.

**Comment by RinChanNOWWW** [comment]
I can help to migrate the trim functions.

**Comment by sundy-li** [comment]
Let's finish this task ASAP.

@b41sh 

- `regexp_instr`, `regexp_like`, `regexp_replace`, `regexp_substr`
 
 
 @sundy-li 
- `conv` 
- `repeat`
- `char`
- `soundex`
-  `ord`,


@andylokandy 
-  `substring`
-  `mid`
-  `substr`  ->  SUBSTRING(str,pos,len).
-  `left`
-  `right` 
-  `space`


@TCeason 

-  `lpad`
-  `rpad`
-  `insert`
-  `replace`
-  `strcmp`
-  `locate`， POSITION(substr IN str) is a synonym for LOCATE(substr,str).
-  `instr` alias `locate`

**Comment by Emanon42** [comment]
Hi @sundy-li, I can help to migrate `repeat`.

**Comment by sundy-li** [comment]
closed in #9411
