### ISSUE TITLE
Tracking issue for Cache-service 

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#6786]
Cache service will be a cluster of data block cache servers sitting in mid of databend-query and underlying storage service to provide fast data block retrieving.

- [x] https://github.com/datafuselabs/databend/pull/6799
- [x] Architecture design: https://github.com/datafuselabs/opencache 
- [ ] Freeze architecture design when the RFC task is closed. 

## Server-side tasks

The following are still some tracking-issue level tasks:(

- [ ] Impl cache replacement policy: modified [LIRS](https://dl.acm.org/doi/10.1145/511399.511340)
- [ ] Impl `Chunk` store. See [arch](https://github.com/datafuselabs/opencache)
- [ ] Impl `Object` store. See [arch](https://github.com/datafuselabs/opencache)
- [ ] Impl `Access` store. See [arch](https://github.com/datafuselabs/opencache)
- [ ] Impl `Manifest` store. See [arch](https://github.com/datafuselabs/opencache)
- [ ] Impl service protocol http2 PUT+GET
- [ ] Impl configuration and server initialization.
- [ ] Impl server restart procedure.

---

Databend side tasks could be found at: https://github.com/datafuselabs/databend/issues/6803

**Comment by flaneur2020** [comment]
beside to accelerating block retrieve from s3, the cache service may also plays the place to store the spilled data from join statemets's shuffle, thus can reduce the OOM caused by skewed joins.

**Comment by drmingdrmer** [comment]
> beside to accelerating block retrieve from s3, the cache service may also plays a good place to store the spilled data from join statemets's shuffle, thus can reduce the OOM caused by skewed joins.

AFAIK, the latest decision about the temp data generated by a `join` is to store them in a persistent store such as `s3`. Since the cache server can not provide a durability guarantee, the temp data has a chance to be evicted when a query execution still needs it.

To support such a requirement, the cache server has to be able to let an application explicitly disable auto eviction for some data. And the application has to purge these caches explicitly when the `join` job is done.

Maybe it can be a future feature that objects have durability configuration?

**Comment by Xuanwo** [comment]
I think `Client side tasks` should be split into two parts:

- OpenDAL's `opencache` service implements `Accessor` based on the `opencache` API.
- Databend's `Temporary Operator` defines cluster metadata format.

> databend-meta support opencache cluster metadata.

Should databend have special knowledge for caching services? Maybe they should be handled inside opendal client?

**Comment by Xuanwo** [comment]
> beside to accelerating block retrieve from s3, the cache service may also plays a good place to store the spilled data from join statemets's shuffle, thus can reduce the OOM caused by skewed joins.

Based on the current design, this feature will be resolved by `Temporary Services`. The query is able to store temporary data:

![image](https://user-images.githubusercontent.com/5351546/180729531-32e84446-1b41-460c-81ad-8348d8a65260.png)

**Comment by drmingdrmer** [comment]
> I think `Client side tasks` should be split into two parts:
> 
> * OpenDAL's `opencache` service implements `Accessor` based on the `opencache` API.
> * Databend's `Temporary Operator` defines cluster metadata format.

Do you mean that `Accessor` only connects to one `opencache` server and lets `Operator` do the load balancing job, such as with a consistent hash?
It would be nice if I understood you correctly.

> > databend-meta support opencache cluster metadata.
> 
> Should databend have special knowledge for caching services? Maybe they should be handled inside opendal client?

I agree:D

**Comment by Xuanwo** [comment]
> Do you mean that `Accessor` only connects to one `opencache` server and lets `Operator` do the load balancing job, such as with a consistent hash?

OpenDAL's opencache client can handle the load balancing job and accept some options:

```toml
[cache]
type = "opencache"

[cache.opencache]
endpoints = ["192.168.0.2", "192.168.0.3"]
hash_methods = "ConsistentHash"
```

**Comment by flaneur2020** [comment]
adding a namespace-like configuration may make operations on a multi-tenant deployment easier:

1. cache keys can be isolated in a different namespaces
2. we can collect some info or restrict usage at the namespace level, like qps, memory limit, rate limit, etc.

**Comment by Xuanwo** [comment]
This tracking issue is composing two things:

- Cache support in Databend
- Distributed Cache services: OpenCache

Maybe we should separate them.

**Comment by Xuanwo** [comment]
> adding a namespace-like configuration may make operations on a multi-tenant deployment easier:

I create a feature request for opencache: https://github.com/datafuselabs/opencache/issues/3

**Comment by drmingdrmer** [comment]
> adding a namespace-like configuration may make operations on a multi-tenant deployment easier:
> 
> 1. cache keys can be isolated in a different namespaces
> 2. we can collect some info or restrict usage at the namespace level, like qps, memory limit, rate limit, etc.

I'd prefer not to introduce namespace into the server side:

- Splitting the cache server disk space into several sub-space reduces resource efficiency. The reserved space in one sub-space can not be used by another heavily loaded sub-space.

- every time a node is added or removed, or a tenant(sub-space) is added or removed, the quota of every sub-space needs to be adjusted.

Maybe it's better to be done on the client side.

**Comment by flaneur2020** [comment]
> Splitting the cache server disk space into several sub-space reduces resource efficienc

oh, do not really need split the storage physically, it can be just a builtin key prefix in the internal storage, like the bucket in boltdb: https://github.com/boltdb/bolt#using-buckets

the operational functionality like quota do not need to be built in the 1st phase, but a design with namespace built-in would make the life easier when multi-tenant workload get into place.

**Comment by flaneur2020** [comment]
> > > Splitting the cache server disk space into several sub-space reduces resource efficienc
> > 
> > 
> > oh, do not really need split the storage physically, it can be just a builtin key prefix in the internal storage, like the bucket in boltdb: https://github.com/boltdb/bolt#using-buckets
> 
> It's different from a db such as bolt: the access load pattern affects the internal data layout. A tenant who reads a lot from the cache server will aggressively evict every piece of other user's data.
> 
> It's not difficult to have a namespace inside the cache server, but it can not be used for throttling without physical isolation.

do our cache service planned to have a proxy layer like twemproxy ? 

if it is, I guess we can do something in the proxy layer to take some control. 

if not, it's hard to maintain the namespace concept in server side IMHO. q.q

**Comment by flaneur2020** [comment]
IMHO a proxy layer do have its complexities and need not to be a high priority work.

another way we may consider is a sidecar proxy to coordinate the multi tenant usages, which more likes a client, it encapsulates the complex part like distributed coordination & billing logic, just offering a simple GET/SET rpc interface.

@zhihanz @hantmac what's your opinion about this? q.q

**Comment by drmingdrmer** [comment]
> do our cache service planned to have a proxy layer like twemproxy ?

Hmm... no such plan yet. Meanwhile the proxy job is done by the opendal.

**Comment by Xuanwo** [comment]
I agree that `namespace`, `proxy`, `quota`, and `audit` are all useful features. But considering our cache services only have markdown docs now, I prefer to start as simple as possible.

Let's implement the cache service and databend's cache mechanism first. After that, we can have a more profound and solid code base for improvement.

What do you think? @flaneur2020 @drmingdrmer

**Comment by Xuanwo** [comment]
Not used so far. Feel free to re-open it when needed.
