### ISSUE TITLE
Tracking issue for Cache Support in databend

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6803]
**Summary**

- [ ] https://github.com/datafuselabs/databend/pull/6799

## Tasks

- [ ] https://github.com/datafuselabs/opendal/issues/382
- [ ] https://github.com/datafuselabs/opendal/issues/467
- [ ] Implement cache and temporary operator in databend
