### ISSUE TITLE
Tracking: Complete RBAC and Ownership model

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#6824]
**Background**

Currently we already have got the RBAC framework on privileges. but still lacks the ownership model and some related stuffs:

- each data object can be owned by an role
- each user can have one session role in a session, all the data objects created by this user is automatically owned by the primary role
- the current role can be switched by `USE ROLE`
- if the current session do not have primary role, it'd default as the DEFAULT role.

**Goal**

- introduce Ownership model into databend
- make it extensible with outer systems

**Tasks**

- [x] https://github.com/datafuselabs/databend/issues/6804
- [x] https://github.com/datafuselabs/databend/issues/6843
- [x] https://github.com/datafuselabs/databend/issues/6864
- [x] https://github.com/datafuselabs/databend/issues/7049
- [x] https://github.com/datafuselabs/databend/issues/6827
- [x] https://github.com/datafuselabs/databend/issues/6991
- [x] https://github.com/datafuselabs/databend/issues/8420
- [ ] https://github.com/datafuselabs/databend/issues/8555
- [ ] Do not merge the inherited privileges in SHOW GRANTS
- [x] https://github.com/datafuselabs/databend/issues/8193
- [ ] ~https://github.com/datafuselabs/databend/issues/6828~ (make DAC a seperate tracking issue)
- [ ] ~https://github.com/datafuselabs/databend/issues/6840~ (low priority)

**Comment by flaneur2020** [comment]
We can add a short docs about RBAC and privileges system like this: https://cwiki.apache.org/confluence/display/Hive/SQL+Standard+Based+Hive+Authorization

**Comment by BohuTANG** [comment]
This issue can be closed? @flaneur2020

**Comment by flaneur2020** [comment]
> This issue can be closed? @flaneur2020

sorry for late response, I think this issue can be closed.

we already have got an working RBAC framework, the related tasks can be issued seperately outside this issue.
