### ISSUE TITLE
Benchmark: Support TPC-DS benchmark in Databend

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6984]
## Summary

TPC-DS is a very challenging benchmark to evaluate OLAP ability of a database system, which involves close to a hundred of complicated SQL queries.

It will be a prove of maturity if we can support TPC-DS perfectly in Databend.

## Task list

- [x] CTE(Common Table Expression) #6246 
- [x] TPC-DS data/query generation tools for Databend
- [x] https://github.com/datafuselabs/databend/issues/10202

**Comment by wubx** [comment]
Awesome

**Comment by leiysky** [comment]
All done.
