### ISSUE TITLE
Feature: Tracking issue for JSON optimization

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#6994]
**Summary**

Optimize JSON read performance by implementing Virtual Column and JSONB binary format

related #5925

## Task list

- [x] [RFC](https://github.com/datafuselabs/databend/pull/6995)
- [ ] FPGrowth algorithm for statistics
- [x] Extract virtual columns
- [x] Push down JSON key path access
- [x] https://github.com/datafuselabs/databend/issues/7668

**Comment by Xuanwo** [comment]
Putting RFC as the first task is excellent!

**Comment by haydenflinner** [comment]
This will be awesome, it's a great usability feature that it's always felt like is possible but seems to be missing in other db/warehouse/lakehouse solutions!
