### ISSUE TITLE
Tracking issues of Databend v0.8 Release Process

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#7053]
We expect to release databend v0.8 next week. However, there are still many works, especially for non-code jobs. This issue tracks the overall release process, so our community will know what we are doing and when they can get and try databend v0.8.

@Xuanwo will take responsibility for the v0.8 release.

Let's rock!

## Tasks

- [x] https://github.com/datafuselabs/databend/issues/4591
  - Make sure all big changes are covered in the v0.8 tracking issue.
- [x] Unstable/Flaky tests cleanup
  - [x] https://github.com/datafuselabs/databend/issues/6733
- [x] Writing Changelogs / Release Notes
- [x] Writing blogs
- [x] Make a tag
- [x] Announce on Twitter and Weixin Official Account

**Comment by Xuanwo** [comment]
Released at: https://github.com/datafuselabs/databend/releases/tag/v0.8.0-nightly
