### ISSUE TITLE
Tracking: Load very large dataset into databend

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7444]
**Summary**

Tasks:
- [x] https://github.com/datafuselabs/databend/issues/6395  @RinChanNOWWW
- [x] https://github.com/datafuselabs/databend/issues/6338 @lichuang 
- [x] https://github.com/datafuselabs/databend/issues/7443 @sundy-li 
- [x] https://github.com/datafuselabs/databend/issues/7228

Flow:
1. kafka/others  sink to s3
2. A cron copies all the files from s3 to databend.
3. databend check the file has loaded or not, if loaded just skip, if not, load it and write the meta to metasrv, after load successful purge the file in the s3.
4. The cron runs again.

**Comment by flaneur2020** [comment]
we can consider make the cron in an external tool to focus on the file discovery in s3 directory.

there're different ways on the file discovery task:

- LIST by incremental (using the start-from in s3 LIST API in the lexicographic order)
  - it's easy to config, but might produce some cost on polling LIST api and takes longer to discover the new files
- use the s3 notification by SQS (it have quicker response)
  - it can discover the new files in a quicker manner, but have more complex configurations and require a seperate dependency on SQS

**Comment by xudong963** [comment]
FYI, I'm testing tpch performance on our cloud but block at `copy` data into table.

```sql
copy into lineitem from @tpch_data files=('tpch100_single/lineitem.tbl') file_format=(type='CSV' field_delimiter='|' record_delimiter='\n');
```
The specific situation is that `lineitem.tbl` contains 76G data and can't copy data into lineitem table.

The above SQL return success, but no data is inserted.

**Comment by BohuTANG** [comment]
I think there are some errors but not return to the client. 

You can try:
`copy into lineitem from @tpch_data files=('tpch100_single/lineitem.tbl') file_format=(type='CSV' field_delimiter='|' record_delimiter='\n') force=true; `

**Comment by BohuTANG** [comment]
All works great now.
