### ISSUE TITLE
Tracking: JSONB format

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#7668]
**Summary**

- [x] https://github.com/datafuselabs/databend/issues/7522
- [x] add more `JSON` test case
- [ ] implement `serde::Serializer` and `serde::Deserializer` for `JSONB` value
- [ ] support json path pushdown to storage layer
