### ISSUE TITLE
Migrate aggregation functions to function-v2

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#7740]
**Summary**

- [x] combinator distinct. #7615
- [x] combinator if. #7615
- [x] count. #7615
- [x] sum. #7615
- [x] avg. #7615
- [x] uniq. #7615
- [x] min, max, any. #7787
- [x] arg_min, arg_max. #7901
- [x] std, stddev, stddev_pop #8034
- [x] covar_pop, covar_samp. #7926
- [x] window_funnel #8034
- [x] retention. #7952

**something may be helpful**

- [x] add `try_downcast_builder` for `ValueType`. #7838
- [x] unit tests for group by. #7845
- [x] ~add Default for ValueType::Scalar or add default_scalar for ValueType.~

**Comment by RinChanNOWWW** [comment]
> - add Default for ValueType::Scalar or add default_scalar for ValueType.
> - add try_downcast_builder for ValueType.

Are these necessary? cc @sundy-li

**Comment by RinChanNOWWW** [comment]
The `Default` bound seems not necessary, and not suitable for `AnyType`. Let's not consider this.

**Comment by TCeason** [comment]
Window funnel assign to @TCeason
