### ISSUE TITLE
Tracking: Large dataset insert and read

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7823]
**Summary**

Insert:
- [x] https://github.com/datafuselabs/databend/issues/7943

Read:
- [x] https://github.com/datafuselabs/databend/issues/7805
- [ ] https://github.com/datafuselabs/databend/issues/7314
- [x] https://github.com/datafuselabs/databend/issues/8229
- [ ] https://github.com/datafuselabs/databend/issues/8696
- [ ] https://github.com/datafuselabs/databend/issues/8817
- [x] https://github.com/datafuselabs/databend/pull/8793
- [ ] https://github.com/datafuselabs/databend/issues/8837
- [x] https://github.com/datafuselabs/databend/pull/9335
- [x] https://github.com/datafuselabs/databend/pull/9353
- [x] https://github.com/datafuselabs/databend/pull/9365
- [x] https://github.com/datafuselabs/databend/pull/9379
- [x] https://github.com/datafuselabs/databend/pull/9412

Unload:
- [x] https://github.com/datafuselabs/databend/issues/7618 

Index:
- [x] https://github.com/datafuselabs/databend/issues/7825
- [x] https://github.com/datafuselabs/databend/issues/7829
- [x] https://github.com/datafuselabs/databend/issues/7748
- [x] https://github.com/datafuselabs/databend/issues/7842
- [x] https://github.com/datafuselabs/databend/pull/7867
- [x] https://github.com/datafuselabs/databend/pull/7893
- [x] https://github.com/datafuselabs/databend/issues/7990
- [x] https://github.com/datafuselabs/databend/issues/8279
- [x] https://github.com/datafuselabs/databend/issues/8465

Data:
- [ ] https://github.com/datafuselabs/databend/issues/7828
- [ ] https://github.com/datafuselabs/databend/issues/7847
- [x] https://github.com/datafuselabs/databend/issues/7899
- [ ] https://github.com/datafuselabs/databend/issues/7889
- [x] https://github.com/datafuselabs/databend/issues/7924
- [ ] https://github.com/datafuselabs/databend/issues/7970
- [ ] https://github.com/datafuselabs/databend/issues/7730
- [x] https://github.com/datafuselabs/databend/issues/8311
- [ ] https://github.com/datafuselabs/databend/issues/8572
- [x] https://github.com/datafuselabs/databend/issues/8574
- [ ] https://github.com/datafuselabs/databend/issues/6395
- [x] https://github.com/datafuselabs/databend/issues/8642
- [ ] https://github.com/datafuselabs/databend/issues/8647

Optimize:
- [x] https://github.com/datafuselabs/databend/issues/7875
- [x] https://github.com/datafuselabs/databend/issues/7914
- [x] https://github.com/datafuselabs/databend/issues/7956
- [ ] https://github.com/datafuselabs/databend/issues/7987
- [x] https://github.com/datafuselabs/databend/issues/8067
- [x] https://github.com/datafuselabs/databend/issues/8108
- [x] https://github.com/datafuselabs/databend/issues/8241
- [x] https://github.com/datafuselabs/databend/issues/8247
- [x] https://github.com/datafuselabs/databend/issues/8414
- [ ] https://github.com/datafuselabs/databend/issues/8415
- [ ] https://github.com/datafuselabs/databend/issues/8426

Bug:
- [x] https://github.com/datafuselabs/databend/issues/8049
- [x] https://github.com/datafuselabs/databend/issues/8053

Metrics:
- [x] https://github.com/datafuselabs/databend/issues/8781

**Comment by BohuTANG** [comment]
Let's continue this work in https://github.com/datafuselabs/databend/issues/9604
