### ISSUE TITLE
Databend performance with 100G tpch dataset

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#8074]
**Summary**
- [ ] https://github.com/datafuselabs/databend/issues/7314
- [x] https://github.com/datafuselabs/databend/issues/8073
- [x] https://github.com/datafuselabs/databend/issues/8077
- [x] https://github.com/datafuselabs/databend/issues/8118
- [ ] https://github.com/datafuselabs/databend/issues/8218
- [ ] https://github.com/datafuselabs/databend/issues/8219
- [ ] https://github.com/datafuselabs/databend/issues/7214
