### ISSUE TITLE
Tracking issue for http handler

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8207]
**Summary**

- [ ] https://github.com/datafuselabs/databend/issues/8206
- [ ] https://github.com/datafuselabs/databend/issues/8195

benefit mostly but not only：

- [ ] https://github.com/datafuselabs/databend/issues/8129
- [ ] https://github.com/datafuselabs/databend/issues/8013

**Comment by youngsofun** [comment]
cc @flaneur2020
