### ISSUE TITLE
Tracking issues of RFC: User Stage

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#8520]
**Summary**

- [x] https://github.com/datafuselabs/databend/pull/8526
- [x] https://github.com/datafuselabs/databend/pull/8550
- [ ] https://github.com/datafuselabs/databend/pull/8556
