### ISSUE TITLE
Migrate planner to new expression

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#8622]
## Tasks

- [x] Lower `Scalar` into `RawExpr`
- [x] Remove dependency of `DataTypeImpl` in binder

**Comment by BohuTANG** [comment]
Does this issue plan to merge `query/planner/*` to `sql/planner/plans`?

**Comment by BohuTANG** [comment]
> Does this issue plan to merge `query/planner/*` to `sql/planner/plans`?

I am working on it: https://github.com/datafuselabs/databend/pull/8660

**Comment by BohuTANG** [comment]
- [ ] Migrate semi-structure `get_path` from `sqlparser` to new parse, cc @b41sh
