### ISSUE TITLE
Feature: improve table function `read_parquet`.

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#9135]
**Summary**

Table function `read_parquet` is introduced by #9080. We need more improvement on it.

- [x] Don't read metadata from files when `read_partitions`, but do this before reading data. #9154
- [x] Support reading parquet files with multiple row groups. #9154
- [ ] Support pushing down filter to parquet reading. #9199
