### ISSUE TITLE
Tracking: enhance sqllogictest framework for databend

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#9174]
**Summary**

The issue is used to track what should we do to enhance our sqllogictest framework, and make life better!

- [x] https://github.com/datafuselabs/databend/pull/9150
- [x] Support complete: https://github.com/risinglightdb/sqllogictest-rs/pull/112  [CLI: support databend](https://github.com/risinglightdb/sqllogictest-rs/issues/120)
- [x] Add README for new sqllogictest framework
- [x] https://github.com/datafuselabs/databend/issues/9287 @Xuanwo 
- [x] https://github.com/datafuselabs/databend/pull/9277 by @sundy-li 
- [x] Remove old logictest framework
- [x] https://github.com/datafuselabs/databend/pull/9342
- [x] Drop all state(database, user, stage) when end of run (success or fail). Drop all tests when finish a test file.
- [x] https://github.com/datafuselabs/databend/pull/9391
- [x] https://github.com/datafuselabs/databend/pull/9374
- [x] add ability to process dynamic query  (maybe need to find a more suitable test framework) **difficult**
- [x] https://github.com/datafuselabs/databend/pull/9400
- [ ] Add random data support so that we can replace some unit tests cases. from @Xuanwo 
- [x] https://github.com/datafuselabs/databend/pull/9408 @xudong963 
- [ ] [Add type checker for results ](https://github.com/datafuselabs/databend/issues/9647) @jun0315

**Comment by xudong963** [comment]
If you have features you want, feel free to comment and we can add it to the tracking : )

**Comment by Xuanwo** [comment]
Add random data support.
