### ISSUE TITLE
Roadmap 2023

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9448]
After a full year of research and development in 2022, the functionality and stability of Databend were significantly enhanced, and several users began using it in production. Databend has helped them greatly **reduce** costs and operational complexity issues.

This is Databend Roadmap in 2023 (discussion).

See also:
* Roadmap 2022: [#3706](https://github.com/datafuselabs/databend/issues/3706)
* Roadmap 2021: [#746](https://github.com/datafuselabs/databend/issues/746)

# Main tasks

## Features

| Task                                                                          | Status      | Comments |
|-------------------------------------------------------------------------------|-------------|----------|
| Update                                                                        | IN PROGRESS |          |
| Merge                                                                         | PLAN        |          |
| Alter table                                                                   | IN PROGRESS |          |
| Window function                                                               | PLAN        |          |
| Lambda function and high-order functions                                      | PLAN        |          |
| TimestampTz data type                                                         | PLAN        |          |
| Decimal data type                                                             | PLAN        |          |
| Materialized view                                                             | PLAN        |          |
| [Support SET_VAR hints](https://github.com/datafuselabs/databend/issues/8833) | PLAN        |          |
| Parquet reader                                                                | PLAN        |          |
| Distributed COPY                                                              | PLAN        |          |
| JSON indexing                                                                 | PLAN        |          |
| DataFrame                                                                     | PLAN        |          |
| Data Sharing(community version)                                               | IN PROGRESS |          |

## Improvements

| Task           | Status      | Comments |
|----------------|-------------|----------|
| New expression | IN PROGRESS |          |
| Error message  | PLAN        |          |

## Planner

| Task                                                                                    | Status      | Comments             |
|-----------------------------------------------------------------------------------------|-------------|----------------------|
| Scalar expression normalization                                                         | PLAN        |                      |
| Column constraint framework                                                             | PLAN        |                      |
| [Functional dependency framework](https://github.com/datafuselabs/databend/issues/7438) | PLAN        |                      |
| Join reorder                                                                            | IN PROGRESS |                      |
| CBO for distributed plan                                                                | PLAN        |                      |
| Support TPC-DS                                                                          | PLAN        |                      |
| Support optimization tracing                                                            | PLAN        | Easy to debug/study. |

## Cache

| Task                | Status  | Comments |
|---------------------|---------|----------|
| Unified cache layer | IN PROGRESS |          |
| Meta data cache     | IN PROGRESS |          |
| Index data cache    | IN PROGRESS |          |
| Block data cache    | PLAN    |          |

## Data Storage

| Task                            | Status | Comments                               |
|---------------------------------|--------|----------------------------------------|
| Fuse engine re-clustering       | PLAN   |                                        |
| Fuse engine orphan data cleanup | PLAN   |                                        |
| Fuse engine segment tree        | PLAN   | Support large dataset(PB) in one table |

## LakeHouse

| Task                               | Status      | Comments |
|------------------------------------|-------------|----------|
| Apache Hive                        | IN PROGRESS |          |
| Apache Iceberg                     | IN PROGRESS |          |
| Querying external storage(Parquet) | IN PROGRESS |          |

## Distributed Query Execution

| Task                 | Status      | Comments |
|----------------------|-------------|----------|
| Visualized profiling | IN PROGRESS |          |
| Aggregation spilling | IN PROGRESS |          |

## Resource Quota

| Task                                     | Status      | Comments |
|------------------------------------------|-------------|----------|
| Session-level quota control (CPU/Memory) | IN PROGRESS |          |
| User-level quota control (CPU/Memory)    | PLAN        |          |

## Integrations

| Task                                      | Status      | Comments |
|-------------------------------------------|-------------|----------|
| Dbt integration                           | IN PROGRESS |          |
| Airbyte integration                       | IN PROGRESS |          |
| Datadog Vector integrate with Rust-driver | IN PROGRESS |          |
| Datax integrate with Java-driver          | IN PROGRESS |          |
| CDC with Flink                            | PLAN        |          |
| CDC with Kafka                            | PLAN        |          |

## Testing

| Task          | Status      | Comments                          |
|---------------|-------------|-----------------------------------|
| SQLlogic Test | IN PROGRESS | Supports more test cases          |
| SQLancer Test | IN PROGRESS | Supports more type and more cases |
| Fuzzer Test   | PLAN        |                                   |

# Releases
- [x] [v0.8 #4591](https://github.com/datafuselabs/databend/issues/4591)
- [x] [v0.7 #3428](https://github.com/datafuselabs/databend/issues/2328)
- [x] [v0.6 #2525](https://github.com/datafuselabs/databend/issues/2525)
- [x] [v0.5 #2257](https://github.com/datafuselabs/databend/issues/2257)

**Comment by flaneur2020** [comment]
any plan about improving concurrency capabilities? so developers can depend on databend to make some data exploring platforms (like google analystics?) on the web.

**Comment by flaneur2020** [comment]
any plan about tuning the metasrv's memory usage? I've got a OOM last week, IMHO it can store most the data in the disk?

**Comment by BohuTANG** [comment]
> any plan about improving concurrency capabilities? so developers can depend on databend to make some data exploring platforms (like google analystics?) on the web.

Added: `Concurrent query enhance`

**Comment by BohuTANG** [comment]
> any plan about tuning the metasrv's memory usage? I've got a OOM last week, IMHO it can store most the data in the disk?

@drmingdrmer will fill the meta section, I think he will do it.

**Comment by yufan022** [comment]
Any plan support `decimal` data type? This is essential If we want to use databend in financial related fields.

**Comment by BohuTANG** [comment]
> Any plan to support `decimal` data type? This is essential If we want to use databend in financial related fields. Will we see it in the first half of the year?

Added to the main task, thanks.

**Comment by flaneur2020** [comment]
will fault tolerance on query processing be planned in 2023?

likewise I have some spot instances, the cluster may handles a shutdowned instance gracefully and not affect the running queries.

**Comment by thatcort** [comment]
Is there a plan for when the vector index feature will be added? It is part of #10689 but doesn't seem to have an associated ticket.
