### ISSUE TITLE
Make `common-meta-app` publicly accessible

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#9467]
We want to build meta migration tools based on `common-meta-app` and `common-meta-types`, so we want to depend on `common-meta-app` crate instead of the whole databend repo.

To make this possible, we need to publish crates for `common-meta-app` under names like `databend-common-meta-app`.

### Release the following dep crates

- [ ] common-meta-app
- [ ] common-datavalues
- [ ] common-arrow
- [ ] common-exception
- [ ] common-hashtable
- [ ] common-base
- [ ] common-io
- [ ] common-meta-types
- [ ] common-meta-stoerr
- [ ] common-storage
- [ ] common-auth
- [ ] common-base
- [ ] common-building

```shell
common-meta-app v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/meta/app)
├── common-datavalues v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/query/datavalues)
│   ├── common-arrow v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/arrow)
│   ├── common-exception v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/exception)
│   │   ├── common-arrow v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/arrow) (*)
│   │   │   │       ├── crypto-common v0.1.6
│   ├── common-hashtable v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/hashtable)
│   │   ├── common-base v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/base)
│   │   │   ├── common-exception v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/exception) (*)
│   │   │   │   │   └── symbolic-common v9.2.1
│   ├── common-io v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/io)
│   │   ├── common-exception v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/exception) (*)
├── common-meta-types v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/meta/types)
│   ├── common-exception v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/exception) (*)
│   ├── common-io v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/io) (*)
│   ├── common-meta-stoerr v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/meta/stoerr)
│   │   ├── common-exception v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/exception) (*)
│   ├── common-storage v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/storage)
│   │   ├── common-arrow v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/arrow) (*)
│   │   ├── common-auth v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/auth)
│   │   │   ├── common-base v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/base) (*)
│   │   ├── common-base v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/base) (*)
│   │   ├── common-exception v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/exception) (*)
│   ├── common-building v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/building)
├── common-storage v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/storage) (*)
├── common-building v0.1.0 (/home/xuanwo/Code/datafuselabs/databend/src/common/building) (*)
```

### Remove the following git deps

- [ ] arrow2
- [ ] parquet2
- [ ] pa
- [ ] sled
- [ ] metrics
- [ ] openraft

```shell
:) cargo tree | rg github
│   │   ├── arrow2 v0.14.2 (https://github.com/jorgecarleitao/arrow2?rev=1b190fc#1b190fc9)
│   │   │   ├── parquet2 v0.17.0 (https://github.com/jorgecarleitao/parquet2?rev=fb08b72#fb08b725)
│   │   ├── pa v0.1.0 (https://github.com/sundy-li/pa?rev=7e98302#7e98302d)
│   │   │   ├── arrow2 v0.14.2 (https://github.com/jorgecarleitao/arrow2?rev=1b190fc#1b190fc9) (*)
│   │   └── parquet2 v0.17.0 (https://github.com/jorgecarleitao/parquet2?rev=fb08b72#fb08b725) (*)
│   │   │   ├── metrics v0.20.1 (https://github.com/datafuse-extras/metrics.git?rev=bc49d03#bc49d036)
│   │   │   │   ├── metrics-macros v0.6.0 (proc-macro) (https://github.com/datafuse-extras/metrics.git?rev=bc49d03#bc49d036)
│   │   ├── sled v0.34.6 (https://github.com/datafuse-extras/sled?tag=v0.34.7-datafuse.1#43fa7250)
│   ├── openraft v0.7.3 (https://github.com/drmingdrmer/openraft?tag=v0.7.4-alpha.3#c6fe29d4)
```

**Comment by Xuanwo** [comment]
We need some hands to help remove the git deps. Can you help to address and remove the git deps?

- @drmingdrmer for `sled` and `openraft`
- @sundy-li for `pa`
- @RinChanNOWWW for `arrow2`
- @dantengsky for `parquet2`

**Comment by drmingdrmer** [comment]
`meta-app-v1 = { git = "https://github.com/datafuselabs/databend", tag = "v0.8.176-nightly", package="common-meta-app" }`

This would be the simplest way to reference an old type.
It looks like we do not need to bother releasing these crates anymore.

**Comment by Xuanwo** [comment]
Nice trick!
