### ISSUE TITLE
Tracking: issues about new expression 

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#9480]
**Summary**

After we merge #9411, it may have some issues to solve before we release the next version of 0.9.

- [x] Delete `functions`, `datablocks` crate and rename `functions-v2`. #9481
- [x] Support `alter table refresh index` to override the indices in new version, instead we have be compatible index in #9511 
- [x]  #9562
- [x] Improve bloom filter to use vectorized & typed hash function rather than hashing the `ScalarRef` enum #9542
- [x] `read_parquet` support read nested datatype. #9486
- [x] functions support set error which respect an option null mask bitmap  during the evaluation  #9501 
- [x] #9483
- [x] https://github.com/datafuselabs/databend/issues/9497
- [x] #9533

Meta-service:

- [x] #9535 
- [x] #9544 
- [x] #9555
- [x] #9506 
- [x] Meta provides a tool to migrate meta between versions. #9489 
- [x] #9498

**Comment by drmingdrmer** [comment]
Update meta-service related task

**Comment by sundy-li** [comment]
> Update meta-service related task: Save the new schema format TableSchema directly to meta-service, without converting back to obsolete DataSchema.

That's ok I think, we can backup the obsolete meta.
