### ISSUE TITLE
refactory: storages submodule refactor

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9523]
**Summary**

Now:
```
├── cache
├── common
├── factory
├── fuse
├── hive
├── index
├── information-schema
├── memory
├── null
├── parquet
├── pruner
├── random
├── share
├── stage
├── system
├── table-meta
└── view
```

to:
```
├── common
│   ├── to here
├── factory
├── fuse
├── hive
├── information-schema
├── memory
├── null
├── parquet
├── random
├── share
├── stage
├── system
└── view
```

Tasks:

- [x] https://github.com/datafuselabs/databend/pull/9525
- [x] storages/index to storages/common/index #9526
- [x] storages/prunner to storages/common/prunner #9526
- [x] storages/cache to storages/common/cache #9526
- [ ] ~remove the `common` prefix from storages~

**Comment by BohuTANG** [comment]
@dantengsky welcome to comments

**Comment by dantengsky** [comment]
looks good to me
