### ISSUE TITLE
Tracking: improve CBO for databend

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#9597]
**Summary**

- [x] https://github.com/datafuselabs/databend/issues/9397
- [x] https://github.com/datafuselabs/databend/pull/9571
- [x] https://github.com/datafuselabs/databend/pull/9398
- [x] https://github.com/datafuselabs/databend/pull/9310
- [x] https://github.com/datafuselabs/databend/issues/9409
- [x] https://github.com/datafuselabs/databend/pull/9625
- [x] https://github.com/datafuselabs/databend/issues/9631
- [x] https://github.com/datafuselabs/databend/issues/9410
- [x] https://github.com/datafuselabs/databend/issues/9599
- [x] https://github.com/datafuselabs/databend/issues/9857
- [x] https://github.com/datafuselabs/databend/issues/9601
- [x] benchmark tpch again!

**Comment by xudong963** [comment]
The last two tasks are not very high priority, I will first use tpch to further tune our CBO.
