### ISSUE TITLE
Tracking: fulltext index

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9811]
**Summary**

- [ ] investigation full-text index crate
     - [ ]  https://github.com/BurntSushi/fst
     - [ ] https://github.com/quantleaf/probly-search
     - [ ] https://github.com/toshi-search
- [ ] create index when block writing
- [ ] data skipping with full-text index

**Comment by BohuTANG** [comment]
move to https://github.com/datafuselabs/databend/issues/14505
